import type { Word } from "../wordTypes";

// ── 초등학교 어휘 (e01–e100) ──────────────────────────────────────────────────
// Grade 3: e01–e25   Grade 4: e26–e50
// Grade 5: e51–e75   Grade 6: e76–e100
// 4 units per grade, ~6–7 words per unit

export const ELEMENTARY_WORDS: Word[] = [

  // ══ Grade 3 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 인사
  { id:"e01", word:"hello",     pronunciation:"/həˈloʊ/",     meaning:"안녕하세요",        example:"Hello! My name is Jimin.",            exampleKorean:"안녕하세요! 저는 지민이에요.",          idiom:"say hello to",       idiomMeaning:"~에게 안부를 전하다",   memoryTip:"헬로~ 처음 만날 때 크게 외쳐요!",            difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사", relatedWords:["e02"] },
  { id:"e02", word:"goodbye",   pronunciation:"/ˌɡʊdˈbaɪ/",   meaning:"안녕히 가세요",     example:"Goodbye! See you tomorrow.",          exampleKorean:"안녕히 가세요! 내일 봐요.",             idiom:"wave goodbye",       idiomMeaning:"손을 흔들며 작별하다",  memoryTip:"굿바이~ 좋게(good) 헤어지는 인사!",         difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사", relatedWords:["e01"] },
  { id:"e03", word:"please",    pronunciation:"/pliːz/",       meaning:"부탁해요",          example:"Please sit down.",                    exampleKorean:"앉아 주세요.",                          idiom:"if you please",      idiomMeaning:"부탁드립니다",          memoryTip:"플리즈~ 무릎 꿇고 간절히 부탁하는 소리!",   difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사" },
  { id:"e04", word:"thank you", pronunciation:"/θæŋk juː/",   meaning:"감사합니다",        example:"Thank you for your help.",            exampleKorean:"도와주셔서 감사합니다.",                idiom:"thank you kindly",   idiomMeaning:"진심으로 감사합니다",   memoryTip:"땡큐~ 탱크처럼 든든한 감사 인사!",          difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사" },
  { id:"e05", word:"sorry",     pronunciation:"/ˈsɒri/",       meaning:"미안합니다",        example:"Sorry, I bumped into you.",           exampleKorean:"미안해요, 부딪혔어요.",                 idiom:"sorry excuse",       idiomMeaning:"변명하다",              memoryTip:"쏘리~ 마음이 아플 때 쓰는 말!",             difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사" },
  { id:"e06", word:"name",      pronunciation:"/neɪm/",        meaning:"이름",              example:"My name is Soyun.",                   exampleKorean:"제 이름은 소윤이에요.",                 idiom:"make a name",        idiomMeaning:"유명해지다",            memoryTip:"네임~ 이름(name)을 크게 써 봐요!",           difficulty:"beginner", level:"elementary", grade:3, unit:1, category:"인사" },

  // Unit 2 — 신체
  { id:"e07", word:"head",  pronunciation:"/hɛd/",    meaning:"머리",  example:"My head hurts today.",          exampleKorean:"오늘 머리가 아파요.",       idiom:"head to toe",     idiomMeaning:"머리부터 발끝까지", memoryTip:"헤드~ 헤드폰은 머리에 써요!",         difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },
  { id:"e08", word:"hand",  pronunciation:"/hænd/",   meaning:"손",   example:"Wash your hands before eating.",exampleKorean:"밥 먹기 전에 손을 씻어요.", idiom:"give a hand",     idiomMeaning:"도와주다",          memoryTip:"핸드~ 핸드폰은 손으로 잡아요!",       difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },
  { id:"e09", word:"eye",   pronunciation:"/aɪ/",     meaning:"눈",   example:"She has bright brown eyes.",    exampleKorean:"그녀는 밝은 갈색 눈이에요.", idiom:"eye-catching",   idiomMeaning:"눈에 띄는",         memoryTip:"아이~ 눈(eye)과 나(I)는 발음이 같아요!", difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },
  { id:"e10", word:"foot",  pronunciation:"/fʊt/",    meaning:"발",   example:"My left foot is bigger.",       exampleKorean:"왼발이 더 커요.",           idiom:"put a foot wrong",idiomMeaning:"실수를 하다",        memoryTip:"풋~ 풋볼(football)은 발로 차는 공!",  difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },
  { id:"e11", word:"ear",   pronunciation:"/ɪər/",    meaning:"귀",   example:"I have a pain in my ear.",      exampleKorean:"귀가 아파요.",              idiom:"keep an ear out", idiomMeaning:"귀를 기울이다",      memoryTip:"이어~ 이어폰은 귀에 꽂아요!",         difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },
  { id:"e12", word:"nose",  pronunciation:"/noʊz/",   meaning:"코",   example:"The dog has a wet nose.",       exampleKorean:"개는 코가 촉촉해요.",        idiom:"nose around",     idiomMeaning:"기웃거리다",         memoryTip:"노즈~ 코(nose)로 냄새를 맡아요!",     difficulty:"beginner", level:"elementary", grade:3, unit:2, category:"신체" },

  // Unit 3 — 색깔
  { id:"e13", word:"red",    pronunciation:"/rɛd/",      meaning:"빨간색", example:"Stop at the red light.",          exampleKorean:"빨간 불에서 멈춰요.",       idiom:"red-handed",       idiomMeaning:"현행범으로",       memoryTip:"레드~ 신호등 빨간불=멈춤!",                 difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },
  { id:"e14", word:"blue",   pronunciation:"/bluː/",     meaning:"파란색", example:"The sky is bright blue.",         exampleKorean:"하늘이 밝은 파란색이에요.", idiom:"out of the blue",  idiomMeaning:"갑자기",           memoryTip:"블루~ 파란 하늘(blue sky)!",               difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },
  { id:"e15", word:"green",  pronunciation:"/ɡriːn/",    meaning:"초록색", example:"Leaves turn green in spring.",    exampleKorean:"봄에 잎이 초록색이 돼요.", idiom:"green thumb",      idiomMeaning:"원예 솜씨",        memoryTip:"그린~ 자연과 나무는 초록(green)!",          difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },
  { id:"e16", word:"yellow", pronunciation:"/ˈjɛloʊ/",   meaning:"노란색", example:"The sun looks yellow.",           exampleKorean:"태양은 노랗게 보여요.",     idiom:"yellow brick road",idiomMeaning:"꿈으로 가는 길",    memoryTip:"옐로우~ 노란 바나나처럼 쨍한 색!",          difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },
  { id:"e17", word:"white",  pronunciation:"/waɪt/",     meaning:"흰색",   example:"Snow is white and soft.",         exampleKorean:"눈은 희고 부드러워요.",     idiom:"white lie",        idiomMeaning:"악의 없는 거짓말",  memoryTip:"화이트~ 흰 종이처럼 깨끗한 색!",            difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },
  { id:"e18", word:"black",  pronunciation:"/blæk/",     meaning:"검은색", example:"My cat is all black.",            exampleKorean:"우리 고양이는 전부 검은색이에요.", idiom:"in the black",idiomMeaning:"흑자 상태",        memoryTip:"블랙~ 블랙홀처럼 어두운 색!",               difficulty:"beginner", level:"elementary", grade:3, unit:3, category:"색깔" },

  // Unit 4 — 가족
  { id:"e19", word:"mother",  pronunciation:"/ˈmʌðər/",   meaning:"어머니",           example:"My mother makes delicious soup.",    exampleKorean:"우리 어머니는 맛있는 국을 끓여요.", idiom:"mother tongue",    idiomMeaning:"모국어",          memoryTip:"마더~ 엄마는 세상에서 제일 소중한 사람!", difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족", relatedWords:["e20"] },
  { id:"e20", word:"father",  pronunciation:"/ˈfɑːðər/",  meaning:"아버지",           example:"My father reads every night.",       exampleKorean:"우리 아버지는 매일 밤 책을 읽어요.", idiom:"father figure",  idiomMeaning:"아버지 같은 사람", memoryTip:"파더~ 파도처럼 든든한 아버지!",          difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족", relatedWords:["e19"] },
  { id:"e21", word:"sister",  pronunciation:"/ˈsɪstər/",  meaning:"언니/누나/여동생", example:"My sister is good at math.",         exampleKorean:"우리 언니는 수학을 잘해요.",         idiom:"sister cities",  idiomMeaning:"자매 도시",        memoryTip:"시스터~ 자매(sister)끼리 항상 함께!",    difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족" },
  { id:"e22", word:"brother", pronunciation:"/ˈbrʌðər/",  meaning:"오빠/형/남동생",   example:"My brother plays basketball.",       exampleKorean:"우리 오빠는 농구를 해요.",           idiom:"big brother",    idiomMeaning:"감시자/형",         memoryTip:"브라더~ 형제(brother)의 의리!",          difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족" },
  { id:"e23", word:"family",  pronunciation:"/ˈfæmɪli/",  meaning:"가족",             example:"We eat together as a family.",       exampleKorean:"우리 가족은 함께 밥을 먹어요.",       idiom:"family tree",    idiomMeaning:"가족 계보",         memoryTip:"패밀리~ 패밀리 레스토랑=가족과 함께!",   difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족" },
  { id:"e24", word:"baby",    pronunciation:"/ˈbeɪbi/",   meaning:"아기",             example:"The baby is laughing.",              exampleKorean:"아기가 웃고 있어요.",                idiom:"baby steps",     idiomMeaning:"아주 작은 진전",    memoryTip:"베이비~ 아기 상어처럼 귀여운!",          difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족" },
  { id:"e25", word:"friend",  pronunciation:"/frɛnd/",    meaning:"친구",             example:"My best friend is very funny.",      exampleKorean:"내 가장 친한 친구는 재미있어요.",     idiom:"fair-weather friend", idiomMeaning:"이기적인 친구",  memoryTip:"프렌드~ 프렌즈처럼 소중한 친구!",        difficulty:"beginner", level:"elementary", grade:3, unit:4, category:"가족" },

  // ══ Grade 4 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 학교
  { id:"e26", word:"teacher",  pronunciation:"/ˈtiːtʃər/",  meaning:"선생님",  example:"My teacher explains very well.",       exampleKorean:"우리 선생님은 설명을 잘 해요.",     idiom:"teacher's pet",  idiomMeaning:"선생님 총애 학생", memoryTip:"티처~ 가르치는(teach) 사람!",         difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },
  { id:"e27", word:"book",     pronunciation:"/bʊk/",        meaning:"책",      example:"I read three books last week.",         exampleKorean:"지난주에 책 세 권을 읽었어요.",     idiom:"by the book",    idiomMeaning:"원칙대로",         memoryTip:"북~ 북마크(bookmark)로 책장을 표시!", difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },
  { id:"e28", word:"class",    pronunciation:"/klæs/",       meaning:"수업/반", example:"English class starts at nine.",        exampleKorean:"영어 수업은 9시에 시작해요.",       idiom:"class act",      idiomMeaning:"훌륭한 행동",      memoryTip:"클래스~ 클래스(수준)가 다른 수업!",    difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },
  { id:"e29", word:"school",   pronunciation:"/skuːl/",      meaning:"학교",    example:"I walk to school every day.",           exampleKorean:"저는 매일 걸어서 학교에 가요.",     idiom:"school of thought", idiomMeaning:"사상의 흐름",   memoryTip:"스쿨~ 스쿨버스는 학교 가는 버스!",    difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },
  { id:"e30", word:"study",    pronunciation:"/ˈstʌdi/",     meaning:"공부하다",example:"I study English every morning.",        exampleKorean:"저는 매일 아침 영어를 공부해요.",  idiom:"study hard",     idiomMeaning:"열심히 공부하다",  memoryTip:"스터디~ 스터디 그룹으로 함께 공부!",  difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },
  { id:"e31", word:"student",  pronunciation:"/ˈstjuːdənt/", meaning:"학생",    example:"Every student raised a hand.",          exampleKorean:"반의 모든 학생이 손을 들었어요.",  idiom:"student body",   idiomMeaning:"전체 학생",        memoryTip:"스튜던트~ 공부하는(study) 사람!",     difficulty:"beginner", level:"elementary", grade:4, unit:1, category:"학교" },

  // Unit 2 — 음식
  { id:"e32", word:"apple",    pronunciation:"/ˈæpəl/",   meaning:"사과",  example:"I eat an apple every day.",          exampleKorean:"저는 매일 사과를 먹어요.",          idiom:"apple of my eye",  idiomMeaning:"눈에 넣어도 안 아픈",  memoryTip:"애플~ 사과(apple)는 빨갛고 달콤해요!", difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },
  { id:"e33", word:"bread",    pronunciation:"/brɛd/",    meaning:"빵",    example:"I bake bread with my mom.",           exampleKorean:"엄마와 함께 빵을 구워요.",          idiom:"bread and butter", idiomMeaning:"생계 수단",            memoryTip:"브레드~ 아침 식사의 기본 빵!",          difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },
  { id:"e34", word:"milk",     pronunciation:"/mɪlk/",    meaning:"우유",  example:"Drink milk for strong bones.",        exampleKorean:"뼈를 튼튼하게 하려면 우유를 마셔요.", idiom:"milk it",          idiomMeaning:"최대한 이용하다",      memoryTip:"밀크~ 하얗고 시원한 우유!",             difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },
  { id:"e35", word:"rice",     pronunciation:"/raɪs/",    meaning:"밥/쌀", example:"We eat rice three times a day.",      exampleKorean:"우리는 하루 세 번 밥을 먹어요.",    idiom:"rice paddy",       idiomMeaning:"논",                   memoryTip:"라이스~ 한국인의 주식은 라이스!",       difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },
  { id:"e36", word:"water",    pronunciation:"/ˈwɔːtər/", meaning:"물",    example:"Drink eight glasses of water a day.", exampleKorean:"하루에 물 여덟 잔을 마셔요.",        idiom:"water under the bridge", idiomMeaning:"지나간 일",       memoryTip:"워터~ 워터파크는 물에서 놀아요!",       difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },
  { id:"e37", word:"lunch",    pronunciation:"/lʌntʃ/",   meaning:"점심",  example:"Let's eat lunch together.",           exampleKorean:"점심 같이 먹어요.",                 idiom:"free lunch",       idiomMeaning:"공짜 점심",            memoryTip:"런치~ 런치 타임은 가장 행복한 시간!",   difficulty:"beginner", level:"elementary", grade:4, unit:2, category:"음식" },

  // Unit 3 — 동물
  { id:"e38", word:"dog",      pronunciation:"/dɔːɡ/",      meaning:"개",    example:"My dog loves to play fetch.",       exampleKorean:"우리 개는 공 던지기를 좋아해요.", idiom:"dog-tired",            idiomMeaning:"매우 피곤한",      memoryTip:"독~ 닥스훈트=개의 종류!",          difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },
  { id:"e39", word:"cat",      pronunciation:"/kæt/",        meaning:"고양이",example:"The cat sleeps on the sofa.",       exampleKorean:"고양이가 소파에서 자요.",         idiom:"cat nap",              idiomMeaning:"짧은 낮잠",        memoryTip:"캣~ 고양이처럼 우아해요!",          difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },
  { id:"e40", word:"bird",     pronunciation:"/bɜːrd/",      meaning:"새",   example:"A bird is singing in the tree.",    exampleKorean:"나무에서 새가 노래해요.",         idiom:"a little bird told me", idiomMeaning:"누군가에게 들었어요", memoryTip:"버드~ 새(bird)는 하늘을 날아요!", difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },
  { id:"e41", word:"fish",     pronunciation:"/fɪʃ/",        meaning:"물고기",example:"I caught a big fish today.",        exampleKorean:"오늘 큰 물고기를 잡았어요.",      idiom:"fish out of water",    idiomMeaning:"어색한 상황의 사람", memoryTip:"피시~ 물속에서 헤엄쳐요!",         difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },
  { id:"e42", word:"rabbit",   pronunciation:"/ˈræbɪt/",     meaning:"토끼", example:"The rabbit has long ears.",         exampleKorean:"토끼는 귀가 길어요.",             idiom:"rabbit hole",          idiomMeaning:"복잡한 상황",      memoryTip:"래빗~ 깡충깡충 뛰는 토끼!",        difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },
  { id:"e43", word:"elephant", pronunciation:"/ˈɛlɪfənt/",   meaning:"코끼리",example:"Elephants never forget.",          exampleKorean:"코끼리는 절대 잊지 않아요.",      idiom:"elephant in the room", idiomMeaning:"모두가 아는 민감한 문제", memoryTip:"엘리펀트~ 코로 물을 뿌리는 코끼리!", difficulty:"beginner", level:"elementary", grade:4, unit:3, category:"동물" },

  // Unit 4 — 동사
  { id:"e44", word:"play",  pronunciation:"/pleɪ/",  meaning:"놀다/연주하다", example:"Let's play in the park after school.", exampleKorean:"학교 끝나고 공원에서 놀아요.", idiom:"play it safe",   idiomMeaning:"안전하게 행동하다", memoryTip:"플레이~ 게임을 플레이하는 것처럼!",  difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e45", word:"run",   pronunciation:"/rʌn/",   meaning:"달리다",        example:"I run every morning for exercise.",    exampleKorean:"운동을 위해 매일 아침 달려요.", idiom:"run out of",     idiomMeaning:"~이 떨어지다",     memoryTip:"런~ 마라톤 선수처럼 런(run)!",      difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e46", word:"jump",  pronunciation:"/dʒʌmp/", meaning:"점프하다",       example:"Can you jump higher than me?",         exampleKorean:"나보다 높이 점프할 수 있어요?", idiom:"jump to conclusions", idiomMeaning:"섣불리 결론짓다", memoryTip:"점프~ 공중에 떠요!",              difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e47", word:"sing",  pronunciation:"/sɪŋ/",   meaning:"노래하다",       example:"She loves to sing in the shower.",     exampleKorean:"그녀는 샤워하면서 노래해요.",   idiom:"sing one's praises", idiomMeaning:"~을 칭찬하다",   memoryTip:"싱~ 입에서 나오는 노래 소리!",     difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e48", word:"read",  pronunciation:"/riːd/",  meaning:"읽다",           example:"Read the question carefully.",         exampleKorean:"문제를 꼼꼼히 읽으세요.",        idiom:"read between the lines", idiomMeaning:"행간을 읽다",   memoryTip:"리드~ 독서(reading)에서 읽다(read)!", difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e49", word:"swim",  pronunciation:"/swɪm/",  meaning:"수영하다",       example:"I swim at the pool twice a week.",     exampleKorean:"일주일에 두 번 수영해요.",       idiom:"swim against the tide", idiomMeaning:"흐름을 거스르다", memoryTip:"스윔~ 수영장에서 스윔(swim)!",    difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },
  { id:"e50", word:"dance", pronunciation:"/dæns/",  meaning:"춤추다",         example:"We dance at every school festival.",   exampleKorean:"학교 축제마다 춤을 춰요.",       idiom:"dance around",    idiomMeaning:"에둘러 말하다",     memoryTip:"댄스~ 몸으로 표현하는 예술!",      difficulty:"beginner", level:"elementary", grade:4, unit:4, category:"동사" },

  // ══ Grade 5 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 장소
  { id:"e51", word:"house",    pronunciation:"/haʊs/",      meaning:"집",     example:"We moved to a new house last year.",    exampleKorean:"작년에 새 집으로 이사했어요.",       idiom:"house warming",    idiomMeaning:"집들이",       memoryTip:"하우스~ 따뜻한 우리 집(house)!",     difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },
  { id:"e52", word:"park",     pronunciation:"/pɑːrk/",     meaning:"공원",   example:"Children play in the park.",            exampleKorean:"아이들이 공원에서 놀아요.",           idiom:"park it",          idiomMeaning:"자리잡고 앉다", memoryTip:"파크~ 공원(park)에서 피크닉!",       difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },
  { id:"e53", word:"market",   pronunciation:"/ˈmɑːrkɪt/",  meaning:"시장",   example:"My grandmother goes to the market.",    exampleKorean:"할머니는 시장에 가세요.",             idiom:"on the market",    idiomMeaning:"판매 중인",    memoryTip:"마켓~ 신선한 채소를 사는 곳!",       difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },
  { id:"e54", word:"library",  pronunciation:"/ˈlaɪbrəri/", meaning:"도서관", example:"I borrow books from the library.",       exampleKorean:"도서관에서 책을 빌려요.",             idiom:"library card",     idiomMeaning:"도서관 카드",  memoryTip:"라이브러리~ 지식의 보물창고!",       difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },
  { id:"e55", word:"hospital", pronunciation:"/ˈhɒspɪtəl/", meaning:"병원",   example:"My dad works at the hospital.",          exampleKorean:"우리 아빠는 병원에서 일해요.",        idiom:"hospital visit",   idiomMeaning:"병문안",       memoryTip:"호스피털~ 아플 때 가는 곳!",         difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },
  { id:"e56", word:"station",  pronunciation:"/ˈsteɪʃən/",  meaning:"역/정류장",example:"We meet at the subway station.",       exampleKorean:"지하철역에서 만나요.",                idiom:"station wagon",    idiomMeaning:"승합차",       memoryTip:"스테이션~ 기차역(station)에서 출발!", difficulty:"easy", level:"elementary", grade:5, unit:1, category:"장소" },

  // Unit 2 — 날씨
  { id:"e57", word:"sunny",  pronunciation:"/ˈsʌni/",   meaning:"맑은/화창한",  example:"It is sunny and warm today.",       exampleKorean:"오늘은 맑고 따뜻해요.",    idiom:"sunny side up",  idiomMeaning:"달걀 프라이",      memoryTip:"써니~ 태양(sun)이 빛나는 날!",   difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },
  { id:"e58", word:"rainy",  pronunciation:"/ˈreɪni/",  meaning:"비 오는",       example:"I forgot my umbrella on a rainy day.", exampleKorean:"비 오는 날 우산을 놓고 왔어요.", idiom:"rainy day", idiomMeaning:"어려운 때",     memoryTip:"레이니~ 비(rain)가 오는 날!",    difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },
  { id:"e59", word:"cloudy", pronunciation:"/ˈklaʊdi/", meaning:"흐린/구름 낀", example:"The sky is cloudy this morning.",    exampleKorean:"오늘 아침 하늘이 흐려요.", idiom:"silver lining",  idiomMeaning:"불행 중 다행",     memoryTip:"클라우디~ 구름(cloud)이 많은 날!", difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },
  { id:"e60", word:"cold",   pronunciation:"/koʊld/",   meaning:"추운/차가운",   example:"It is very cold in January.",       exampleKorean:"1월은 매우 추워요.",        idiom:"cold shoulder",  idiomMeaning:"냉대하다",         memoryTip:"콜드~ 겨울에 콜드(cold)!",       difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },
  { id:"e61", word:"hot",    pronunciation:"/hɒt/",     meaning:"더운/뜨거운",  example:"It is too hot to play outside.",    exampleKorean:"너무 더워서 밖에서 놀기 힘들어요.", idiom:"in hot water",idiomMeaning:"곤경에 처한",    memoryTip:"핫~ 여름에 핫(hot)!",           difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },
  { id:"e62", word:"windy",  pronunciation:"/ˈwɪndi/",  meaning:"바람이 부는",   example:"It is windy by the sea.",           exampleKorean:"바닷가에 바람이 많이 불어요.", idiom:"windy road",   idiomMeaning:"구불구불한 길",    memoryTip:"윈디~ 바람(wind)이 부는 날!",    difficulty:"easy", level:"elementary", grade:5, unit:2, category:"날씨" },

  // Unit 3 — 형용사
  { id:"e63", word:"big",   pronunciation:"/bɪɡ/",   meaning:"큰",      example:"This is a big school.",           exampleKorean:"이것은 큰 학교예요.",    idiom:"big picture",   idiomMeaning:"전체적인 시각",  memoryTip:"빅~ 빅맥처럼 큰!",            difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },
  { id:"e64", word:"small", pronunciation:"/smɔːl/", meaning:"작은",    example:"My room is small but cozy.",      exampleKorean:"내 방은 작지만 아늑해요.", idiom:"small talk",    idiomMeaning:"가벼운 대화",    memoryTip:"스몰~ 스몰 사이즈=작은 것!",  difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },
  { id:"e65", word:"tall",  pronunciation:"/tɔːl/",  meaning:"키가 큰/높은", example:"My dad is very tall.",       exampleKorean:"우리 아빠는 키가 매우 커요.", idiom:"tall order", idiomMeaning:"어려운 요구",    memoryTip:"톨~ 톨 사이즈 커피처럼 높은!", difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },
  { id:"e66", word:"short", pronunciation:"/ʃɔːrt/", meaning:"짧은/키가 작은", example:"This skirt is too short.", exampleKorean:"이 치마는 너무 짧아요.",  idiom:"shortcut",      idiomMeaning:"지름길",         memoryTip:"쇼트~ 쇼트 헤어처럼 짧은!",   difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },
  { id:"e67", word:"fast",  pronunciation:"/fæst/",  meaning:"빠른",    example:"The cheetah is the fastest animal.", exampleKorean:"치타는 가장 빠른 동물이에요.", idiom:"fast track", idiomMeaning:"빠른 승진 코스", memoryTip:"패스트~ 패스트푸드처럼 빠른!", difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },
  { id:"e68", word:"slow",  pronunciation:"/sloʊ/",  meaning:"느린",    example:"A turtle walks very slow.",       exampleKorean:"거북이는 아주 느리게 걸어요.", idiom:"slow down",  idiomMeaning:"속도를 줄이다",  memoryTip:"슬로우~ 슬로우(slow)=느리다!", difficulty:"easy", level:"elementary", grade:5, unit:3, category:"형용사" },

  // Unit 4 — 시간
  { id:"e69", word:"morning",   pronunciation:"/ˈmɔːrnɪŋ/", meaning:"아침",  example:"I brush my teeth every morning.",     exampleKorean:"매일 아침 이를 닦아요.",          idiom:"morning person",  idiomMeaning:"아침형 인간",    memoryTip:"모닝~ 모닝 커피처럼 상쾌한 아침!",  difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e70", word:"evening",   pronunciation:"/ˈiːvnɪŋ/",  meaning:"저녁",  example:"My family watches TV in the evening.", exampleKorean:"우리 가족은 저녁에 TV를 봐요.",   idiom:"evening wear",    idiomMeaning:"저녁 예복",      memoryTip:"이브닝~ 하루의 끝 무렵!",          difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e71", word:"week",      pronunciation:"/wiːk/",      meaning:"주/일주일", example:"There are seven days in a week.",  exampleKorean:"일주일은 7일이에요.",             idiom:"week in week out", idiomMeaning:"매주",          memoryTip:"위크~ 일주일(week)!",               difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e72", word:"today",     pronunciation:"/təˈdeɪ/",    meaning:"오늘",  example:"Today is a beautiful day.",          exampleKorean:"오늘은 날씨가 정말 좋아요.",      idiom:"today's special",  idiomMeaning:"오늘의 특별 메뉴", memoryTip:"투데이~ 오늘(today)=지금 이 순간!", difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e73", word:"yesterday", pronunciation:"/ˈjɛstərdeɪ/",meaning:"어제",  example:"I forgot my homework yesterday.",    exampleKorean:"어제 숙제를 잊어버렸어요.",        idiom:"yesterday's news", idiomMeaning:"구식인 것",      memoryTip:"예스터데이~ 비틀즈 노래처럼 지난 날!", difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e74", word:"tomorrow",  pronunciation:"/təˈmɒroʊ/",  meaning:"내일",  example:"Tomorrow is my birthday.",           exampleKorean:"내일은 제 생일이에요.",            idiom:"never put off",    idiomMeaning:"내일로 미루지 마라", memoryTip:"투모로우~ 미래의 내일!",            difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },
  { id:"e75", word:"year",      pronunciation:"/jɪər/",       meaning:"해/년", example:"The new year starts on January 1st.", exampleKorean:"새해는 1월 1일에 시작해요.",       idiom:"year round",       idiomMeaning:"일년 내내",      memoryTip:"이어~ 이어(year)=일년!",            difficulty:"easy", level:"elementary", grade:5, unit:4, category:"시간" },

  // ══ Grade 6 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 자연
  { id:"e76", word:"mountain", pronunciation:"/ˈmaʊntɪn/", meaning:"산",  example:"Hiking in the mountain is fun.",    exampleKorean:"산 등반은 재미있어요.",       idiom:"move mountains", idiomMeaning:"불가능을 해내다", memoryTip:"마운틴~ 높은 산(mountain)!",         difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },
  { id:"e77", word:"river",    pronunciation:"/ˈrɪvər/",   meaning:"강",  example:"We picnicked by the river.",        exampleKorean:"강가에서 소풍을 했어요.",     idiom:"sell down the river", idiomMeaning:"배신하다",   memoryTip:"리버~ 강(river)은 흘러가요!",        difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },
  { id:"e78", word:"sea",      pronunciation:"/siː/",      meaning:"바다", example:"The sea is calm today.",           exampleKorean:"오늘 바다가 잔잔해요.",       idiom:"sea change",     idiomMeaning:"큰 변화",        memoryTip:"씨~ 바다(sea)는 끝없이 넓어요!",     difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },
  { id:"e79", word:"flower",   pronunciation:"/ˈflaʊər/",  meaning:"꽃",  example:"She gave me a bunch of flowers.",  exampleKorean:"그녀가 꽃다발을 주었어요.",   idiom:"flower power",   idiomMeaning:"평화와 사랑의 힘",  memoryTip:"플라워~ 예쁜 꽃(flower)!",           difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },
  { id:"e80", word:"tree",     pronunciation:"/triː/",     meaning:"나무", example:"We planted a tree for Earth Day.", exampleKorean:"지구의 날에 나무를 심었어요.", idiom:"tree hugger",    idiomMeaning:"환경 운동가",      memoryTip:"트리~ 크리스마스 트리(tree)=나무!",  difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },
  { id:"e81", word:"sky",      pronunciation:"/skaɪ/",     meaning:"하늘", example:"The sky is full of stars tonight.", exampleKorean:"오늘 밤 하늘에 별이 가득해요.", idiom:"sky's the limit", idiomMeaning:"한계가 없다",   memoryTip:"스카이~ 하늘(sky)! 스카이다이빙!",   difficulty:"easy", level:"elementary", grade:6, unit:1, category:"자연" },

  // Unit 2 — 취미
  { id:"e82", word:"soccer",   pronunciation:"/ˈsɒkər/",    meaning:"축구",   example:"My class plays soccer during PE.",   exampleKorean:"우리 반은 체육 시간에 축구를 해요.", idiom:"soccer mom",       idiomMeaning:"아이 활동을 뒷바라지하는 엄마", memoryTip:"사커~ 발로 차는 공!",          difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },
  { id:"e83", word:"swimming", pronunciation:"/ˈswɪmɪŋ/",   meaning:"수영",   example:"Swimming is great exercise in summer.", exampleKorean:"수영은 여름에 훌륭한 운동이에요.", idiom:"swimming in",   idiomMeaning:"~이 넘치는",    memoryTip:"스위밍~ 물속에서 헤엄치기!",   difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },
  { id:"e84", word:"music",    pronunciation:"/ˈmjuːzɪk/",  meaning:"음악",   example:"I listen to music before sleeping.",  exampleKorean:"자기 전에 음악을 들어요.",           idiom:"music to one's ears", idiomMeaning:"반가운 소식",  memoryTip:"뮤직~ 아름다운 소리!",          difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },
  { id:"e85", word:"art",      pronunciation:"/ɑːrt/",       meaning:"미술/예술",example:"She is talented in art.",          exampleKorean:"그녀는 미술에 재능이 있어요.",       idiom:"state of the art", idiomMeaning:"최첨단의",      memoryTip:"아트~ 예술(art)은 마음을 풍요롭게!", difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },
  { id:"e86", word:"cooking",  pronunciation:"/ˈkʊkɪŋ/",    meaning:"요리",   example:"Cooking with family is enjoyable.",   exampleKorean:"가족과 함께 요리하는 건 즐거워요.", idiom:"what's cooking?",  idiomMeaning:"무슨 일이야?",  memoryTip:"쿠킹~ 부엌에서 뚝딱!",         difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },
  { id:"e87", word:"reading",  pronunciation:"/ˈriːdɪŋ/",   meaning:"독서",   example:"Reading expands your knowledge.",     exampleKorean:"독서는 지식을 넓혀 줘요.",           idiom:"a good read",      idiomMeaning:"재미있는 책",    memoryTip:"리딩~ 독서(reading)=책 읽기!",  difficulty:"easy", level:"elementary", grade:6, unit:2, category:"취미" },

  // Unit 3 — 건강
  { id:"e88", word:"sick",      pronunciation:"/sɪk/",       meaning:"아픈",    example:"I stayed home because I was sick.",    exampleKorean:"아파서 집에 있었어요.",            idiom:"sick and tired",    idiomMeaning:"지겨운",           memoryTip:"식~ 아플 때 먹는 죽처럼!",         difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },
  { id:"e89", word:"doctor",    pronunciation:"/ˈdɒktər/",   meaning:"의사",    example:"The doctor checked my temperature.",   exampleKorean:"의사가 체온을 확인했어요.",         idiom:"just what the doctor ordered", idiomMeaning:"딱 필요한 것",  memoryTip:"닥터~ 아플 때 만나는 분!",         difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },
  { id:"e90", word:"medicine",  pronunciation:"/ˈmɛdɪsɪn/",  meaning:"약",      example:"Take this medicine twice a day.",      exampleKorean:"이 약을 하루에 두 번 드세요.",      idiom:"medicine chest",    idiomMeaning:"약장",             memoryTip:"메디신~ 몸을 낫게 하는 약!",       difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },
  { id:"e91", word:"exercise",  pronunciation:"/ˈɛksərsaɪz/",meaning:"운동하다", example:"I exercise for thirty minutes a day.", exampleKorean:"매일 30분씩 운동해요.",             idiom:"exercise caution",  idiomMeaning:"주의를 기울이다",  memoryTip:"엑서사이즈~ 운동하면 건강해요!",    difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },
  { id:"e92", word:"sleep",     pronunciation:"/sliːp/",      meaning:"자다/수면",example:"Children need at least nine hours of sleep.", exampleKorean:"어린이는 9시간은 자야 해요.", idiom:"sleep on it",       idiomMeaning:"하룻밤 생각하다", memoryTip:"슬립~ 꿈나라로!",                  difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },
  { id:"e93", word:"healthy",   pronunciation:"/ˈhɛlθi/",    meaning:"건강한",  example:"Eating vegetables keeps you healthy.", exampleKorean:"채소를 먹으면 건강해요.",           idiom:"healthy lifestyle", idiomMeaning:"건강한 생활방식", memoryTip:"헬씨~ 헬스=건강! 건강한(healthy)!", difficulty:"easy", level:"elementary", grade:6, unit:3, category:"건강" },

  // Unit 4 — 지역사회
  { id:"e94",  word:"city",       pronunciation:"/ˈsɪti/",       meaning:"도시",  example:"Seoul is a very busy city.",          exampleKorean:"서울은 매우 바쁜 도시예요.",    idiom:"city slicker",     idiomMeaning:"도시 사람",      memoryTip:"씨티~ 씨티(city)=도시!",             difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e95",  word:"store",      pronunciation:"/stɔːr/",       meaning:"가게",  example:"I bought pencils at the school store.", exampleKorean:"학교 매점에서 연필을 샀어요.",  idiom:"store up",         idiomMeaning:"저장해 두다",    memoryTip:"스토어~ 물건 파는 가게(store)!",     difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e96",  word:"restaurant", pronunciation:"/ˈrɛstrɒnt/",  meaning:"음식점", example:"We ate at a Korean restaurant.",       exampleKorean:"한식당에서 먹었어요.",           idiom:"restaurant quality", idiomMeaning:"레스토랑 수준", memoryTip:"레스토랑~ 맛있는 음식을 먹는 곳!",   difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e97",  word:"bus",        pronunciation:"/bʌs/",         meaning:"버스",  example:"I take the bus to school every day.",  exampleKorean:"매일 버스를 타고 학교에 가요.",  idiom:"miss the bus",     idiomMeaning:"기회를 놓치다",  memoryTip:"버스~ 버스를 놓치면 안 돼요!",       difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e98",  word:"police",     pronunciation:"/pəˈliːs/",     meaning:"경찰",  example:"The police helped find the lost child.", exampleKorean:"경찰이 미아를 찾아줬어요.",    idiom:"police state",     idiomMeaning:"경찰 국가",      memoryTip:"폴리스~ 법을 지키는 사람들!",        difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e99",  word:"fire",       pronunciation:"/faɪər/",       meaning:"불/화재",example:"Call 119 if there is a fire.",         exampleKorean:"화재가 나면 119에 전화해요.",   idiom:"fight fire with fire", idiomMeaning:"이에는 이",  memoryTip:"파이어~ 뜨거운 불(fire)!",           difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },
  { id:"e100", word:"bridge",     pronunciation:"/brɪdʒ/",       meaning:"다리",  example:"We cross the bridge to get to school.", exampleKorean:"학교에 가려면 다리를 건너요.",  idiom:"burn bridges",     idiomMeaning:"관계를 끊다",    memoryTip:"브리지~ 강 위에 놓인 다리(bridge)!", difficulty:"easy", level:"elementary", grade:6, unit:4, category:"지역사회" },

];
