import type { Word } from "../wordTypes";

// ── 고등학교 어휘 (h01–h100) ──────────────────────────────────────────────────
// Grade 1: h01–h33   Grade 2: h34–h66   Grade 3: h67–h100
// 4 units per grade, 8–9 words per unit

export const HIGH1_WORDS: Word[] = [

  // ══ Grade 1 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 학술동사
  { id:"h01", word:"achieve",     pronunciation:"/əˈtʃiːv/",        meaning:"달성하다",     example:"She achieved her dream of becoming a doctor.", exampleKorean:"그녀는 의사가 되는 꿈을 이루었어요.",    idiom:"high achiever",     idiomMeaning:"뛰어난 성취자",    memoryTip:"어치브~ 목표에 다가가 달성하다!",        difficulty:"medium", level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h02", word:"demonstrate", pronunciation:"/ˈdɛmənstreɪt/",   meaning:"보여주다/증명하다", example:"He demonstrated his skills in the exam.",  exampleKorean:"그는 시험에서 실력을 증명했어요.",      idiom:"product demonstration", idiomMeaning:"제품 시연",   memoryTip:"데몬스트레이트~ 데모(demo)=직접 보여주기!", difficulty:"medium", level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h03", word:"analyze",     pronunciation:"/ˈænəlaɪz/",       meaning:"분석하다",     example:"We analyzed the data carefully.",              exampleKorean:"우리는 데이터를 꼼꼼히 분석했어요.",    idiom:"data analysis",     idiomMeaning:"데이터 분석",      memoryTip:"애널라이즈~ 애널리스트처럼 분석하다!",   difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h04", word:"evaluate",    pronunciation:"/ɪˈvæljʊeɪt/",    meaning:"평가하다",     example:"Teachers evaluate students fairly.",           exampleKorean:"선생님은 학생을 공정하게 평가해요.",    idiom:"performance evaluation", idiomMeaning:"성과 평가", memoryTip:"이밸류에이트~ 가치(value)를 따져 평가!", difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h05", word:"establish",   pronunciation:"/ɪˈstæblɪʃ/",     meaning:"설립하다/확립하다", example:"The school established a new science lab.", exampleKorean:"학교가 새 과학실을 설립했어요.",        idiom:"well-established",  idiomMeaning:"잘 확립된",        memoryTip:"이스태블리시~ 안정되게 세우다!",         difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h06", word:"identify",    pronunciation:"/aɪˈdɛntɪfaɪ/",   meaning:"파악하다/식별하다", example:"Can you identify the main problem?",      exampleKorean:"주요 문제를 파악할 수 있어요?",         idiom:"identify with",     idiomMeaning:"동일시하다",       memoryTip:"아이덴티파이~ 정체(identity)를 밝히다!", difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h07", word:"determine",   pronunciation:"/dɪˈtɜːrmɪn/",    meaning:"결정하다/알아내다", example:"Scientists determine the age of fossils.", exampleKorean:"과학자들은 화석의 나이를 알아내요.",   idiom:"determined attitude",idiomMeaning:"굳은 태도",        memoryTip:"디터민~ 완전히 결론 내다!",              difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },
  { id:"h08", word:"implement",   pronunciation:"/ˈɪmplɪmənt/",    meaning:"실행하다/시행하다", example:"We will implement the new plan next month.", exampleKorean:"다음 달에 새 계획을 시행할 거예요.",  idiom:"full implementation",idiomMeaning:"전면 시행",        memoryTip:"임플리먼트~ 계획을 실행에 옮기다!",      difficulty:"hard",   level:"high", grade:1, unit:1, category:"학술동사" },

  // Unit 2 — 사회문제
  { id:"h09", word:"equality",       pronunciation:"/ɪˈkwɒlɪti/",      meaning:"평등",         example:"Equality means treating everyone fairly.",    exampleKorean:"평등은 모든 사람을 공정하게 대하는 것이에요.", idiom:"gender equality",  idiomMeaning:"성 평등",         memoryTip:"이퀄리티~ 이퀄(equal=같은)+리티=같은 권리!", difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h10", word:"justice",        pronunciation:"/ˈdʒʌstɪs/",       meaning:"정의/공정",    example:"Justice must be served for all.",             exampleKorean:"모두를 위해 정의가 실현되어야 해요.",    idiom:"social justice",    idiomMeaning:"사회 정의",        memoryTip:"저스티스~ 옳고 공정한 것!",              difficulty:"medium", level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h11", word:"poverty",        pronunciation:"/ˈpɒvərti/",       meaning:"빈곤",         example:"Poverty is a serious global issue.",           exampleKorean:"빈곤은 심각한 세계적 문제예요.",         idiom:"extreme poverty",   idiomMeaning:"극빈",             memoryTip:"파버티~ 가난(poor)한 상태!",              difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h12", word:"opportunity",    pronunciation:"/ˌɒpərˈtjuːnɪti/", meaning:"기회",         example:"Everyone deserves equal opportunity.",         exampleKorean:"모든 사람은 평등한 기회를 가질 자격이 있어요.", idiom:"window of opportunity", idiomMeaning:"기회의 창",  memoryTip:"오퍼튜니티~ 문이 열린 기회!",            difficulty:"medium", level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h13", word:"discrimination", pronunciation:"/dɪˌskrɪmɪˈneɪʃən/", meaning:"차별",      example:"Discrimination based on race is wrong.",       exampleKorean:"인종에 기반한 차별은 옳지 않아요.",      idiom:"racial discrimination", idiomMeaning:"인종 차별",   memoryTip:"디스크리미네이션~ 부당하게 구분짓기!",  difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h14", word:"diversity",      pronunciation:"/daɪˈvɜːrsɪti/",   meaning:"다양성",       example:"Diversity makes a society stronger.",          exampleKorean:"다양성은 사회를 더 강하게 만들어요.",    idiom:"cultural diversity",idiomMeaning:"문화적 다양성",    memoryTip:"다이버시티~ 다양한(diverse) 사람들!",    difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h15", word:"inclusion",      pronunciation:"/ɪnˈkluːʒən/",     meaning:"포용/포함",    example:"Inclusion means everyone belongs.",            exampleKorean:"포용이란 모두가 속한다는 의미예요.",      idiom:"inclusive society", idiomMeaning:"포용 사회",        memoryTip:"인클루전~ 모두를 안으로 받아들임!",      difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },
  { id:"h16", word:"welfare",        pronunciation:"/ˈwɛlfeər/",       meaning:"복지/안녕",    example:"The welfare of citizens is the government's job.", exampleKorean:"시민의 복지는 정부의 역할이에요.",  idiom:"social welfare",    idiomMeaning:"사회 복지",        memoryTip:"웰페어~ 잘(well) 지내도록 돕는 것!",    difficulty:"hard",   level:"high", grade:1, unit:2, category:"사회문제" },

  // Unit 3 — 환경
  { id:"h17", word:"sustainable",  pronunciation:"/səˈsteɪnəbəl/",  meaning:"지속 가능한",  example:"Renewable energy is a sustainable solution.",  exampleKorean:"재생 에너지는 지속 가능한 해결책이에요.", idiom:"sustainable development", idiomMeaning:"지속 가능한 발전", memoryTip:"서스테이너블~ 유지 가능한(sustain+able)!", difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h18", word:"ecosystem",    pronunciation:"/ˈiːkoʊˌsɪstəm/", meaning:"생태계",       example:"Forests are vital for the ecosystem.",         exampleKorean:"숲은 생태계에 매우 중요해요.",            idiom:"balanced ecosystem",idiomMeaning:"균형 잡힌 생태계", memoryTip:"에코시스템~ 에코(환경)+시스템!",          difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h19", word:"renewable",    pronunciation:"/rɪˈnjuːəbəl/",   meaning:"재생 가능한",  example:"Wind and solar are renewable energy sources.", exampleKorean:"풍력과 태양광은 재생 가능한 에너지원이에요.", idiom:"renewable resource", idiomMeaning:"재생 자원",  memoryTip:"리뉴어블~ 다시 새로워지는(re+new)!",     difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h20", word:"extinct",      pronunciation:"/ɪkˈstɪŋkt/",     meaning:"멸종된",       example:"Dinosaurs became extinct millions of years ago.", exampleKorean:"공룡은 수백만 년 전에 멸종됐어요.",    idiom:"extinct species",   idiomMeaning:"멸종 종",          memoryTip:"익스팅크트~ 완전히 꺼진(ex+stinct)!",   difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h21", word:"biodiversity", pronunciation:"/ˌbaɪoʊdaɪˈvɜːrsɪti/", meaning:"생물 다양성", example:"Biodiversity is essential for healthy ecosystems.", exampleKorean:"생물 다양성은 건강한 생태계에 필수적이에요.", idiom:"loss of biodiversity", idiomMeaning:"생물 다양성 손실", memoryTip:"바이오다이버시티~ 생명(bio)+다양성!", difficulty:"advanced", level:"high", grade:1, unit:3, category:"환경" },
  { id:"h22", word:"atmosphere",   pronunciation:"/ˈætməsfɪər/",    meaning:"대기/분위기",  example:"Greenhouse gases trap heat in the atmosphere.", exampleKorean:"온실가스는 대기에 열을 가두어요.",        idiom:"tense atmosphere",  idiomMeaning:"긴장된 분위기",    memoryTip:"애트머스피어~ 지구를 감싼 공기층!",      difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h23", word:"emission",     pronunciation:"/ɪˈmɪʃən/",       meaning:"배출(량)",     example:"Cars produce harmful carbon emissions.",        exampleKorean:"자동차는 유해한 탄소를 배출해요.",        idiom:"carbon emission",   idiomMeaning:"탄소 배출",        memoryTip:"이미션~ 밖으로 내보내는(emit) 것!",      difficulty:"hard",     level:"high", grade:1, unit:3, category:"환경" },
  { id:"h24", word:"solution",     pronunciation:"/səˈluːʃən/",     meaning:"해결책",       example:"We need creative solutions to climate issues.", exampleKorean:"환경 문제에 창의적인 해결책이 필요해요.",  idiom:"find a solution",   idiomMeaning:"해결책을 찾다",    memoryTip:"솔루션~ 솔브(solve=해결)하는 방법!",     difficulty:"medium",   level:"high", grade:1, unit:3, category:"환경" },

  // Unit 4 — 경제
  { id:"h25", word:"economy",       pronunciation:"/ɪˈkɒnəmi/",       meaning:"경제",         example:"The global economy has grown rapidly.",        exampleKorean:"세계 경제가 빠르게 성장했어요.",          idiom:"economy class",    idiomMeaning:"일반석",          memoryTip:"이코노미~ 살림살이 관리(eco+nomy)!",     difficulty:"medium", level:"high", grade:1, unit:4, category:"경제" },
  { id:"h26", word:"inflation",     pronunciation:"/ɪnˈfleɪʃən/",    meaning:"인플레이션",   example:"Inflation makes everything more expensive.",   exampleKorean:"인플레이션은 모든 것을 더 비싸게 만들어요.", idiom:"inflation rate",  idiomMeaning:"물가 상승률",     memoryTip:"인플레이션~ 가격이 부풀어오름(inflate)!", difficulty:"hard",   level:"high", grade:1, unit:4, category:"경제" },
  { id:"h27", word:"investment",    pronunciation:"/ɪnˈvɛstmənt/",   meaning:"투자",         example:"Education is the best investment.",            exampleKorean:"교육이 최고의 투자예요.",                 idiom:"return on investment", idiomMeaning:"투자 수익률",  memoryTip:"인베스트먼트~ 돈을 넣는(invest) 행위!", difficulty:"hard",   level:"high", grade:1, unit:4, category:"경제" },
  { id:"h28", word:"unemployment",  pronunciation:"/ˌʌnɪmˈplɔɪmənt/",meaning:"실업",         example:"Youth unemployment is rising in many countries.", exampleKorean:"많은 나라에서 청년 실업이 증가해요.",  idiom:"unemployment rate",idiomMeaning:"실업률",          memoryTip:"언임플로이먼트~ 고용(employ)되지 않음!", difficulty:"hard",   level:"high", grade:1, unit:4, category:"경제" },
  { id:"h29", word:"development",   pronunciation:"/dɪˈvɛləpmənt/",  meaning:"발전/개발",    example:"Sustainable development is a global goal.",    exampleKorean:"지속 가능한 발전은 전 세계의 목표예요.",  idiom:"economic development", idiomMeaning:"경제 발전",   memoryTip:"디벨롭먼트~ 성장하는(develop) 것!",     difficulty:"medium", level:"high", grade:1, unit:4, category:"경제" },
  { id:"h30", word:"resource",      pronunciation:"/ˈriːsɔːrs/",     meaning:"자원",         example:"Natural resources are limited.",               exampleKorean:"천연 자원은 한정되어 있어요.",            idiom:"human resources",  idiomMeaning:"인적 자원",       memoryTip:"리소스~ 다시 쓸 수 있는 원천(source)!", difficulty:"medium", level:"high", grade:1, unit:4, category:"경제" },
  { id:"h31", word:"manufacture",   pronunciation:"/ˌmænjʊˈfæktʃər/",meaning:"제조하다",     example:"Korea manufactures world-class products.",     exampleKorean:"한국은 세계적 수준의 제품을 제조해요.",   idiom:"manufacturing industry", idiomMeaning:"제조업",     memoryTip:"매뉴팩처~ 손(manu)으로 만들다(facture)!", difficulty:"hard",   level:"high", grade:1, unit:4, category:"경제" },
  { id:"h32", word:"export",        pronunciation:"/ˈɛkspɔːrt/",     meaning:"수출하다/수출", example:"Korea exports cars and electronics.",          exampleKorean:"한국은 자동차와 전자제품을 수출해요.",    idiom:"export market",    idiomMeaning:"수출 시장",       memoryTip:"익스포트~ 항구(port) 밖으로(ex) 보내다!", difficulty:"medium", level:"high", grade:1, unit:4, category:"경제" },
  { id:"h33", word:"import",        pronunciation:"/ˈɪmpɔːrt/",      meaning:"수입하다/수입", example:"We import coffee from South America.",          exampleKorean:"우리는 남미에서 커피를 수입해요.",        idiom:"import tax",       idiomMeaning:"수입세",          memoryTip:"임포트~ 항구(port) 안으로(im) 들여오다!", difficulty:"medium", level:"high", grade:1, unit:4, category:"경제" },

  // ══ Grade 2 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 윤리
  { id:"h34", word:"moral",          pronunciation:"/ˈmɒrəl/",        meaning:"도덕적인/교훈", example:"Be a person of high moral values.",           exampleKorean:"도덕적 가치가 높은 사람이 되세요.",      idiom:"moral dilemma",     idiomMeaning:"도덕적 딜레마",   memoryTip:"모럴~ 옳고 그름을 따지는 도덕!",         difficulty:"medium", level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h35", word:"ethical",        pronunciation:"/ˈɛθɪkəl/",       meaning:"윤리적인",     example:"Doctors must make ethical decisions.",        exampleKorean:"의사는 윤리적인 결정을 내려야 해요.",    idiom:"ethical behavior",  idiomMeaning:"윤리적 행동",     memoryTip:"에시컬~ 윤리(ethics)에 관한!",            difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h36", word:"principle",      pronunciation:"/ˈprɪnsɪpəl/",    meaning:"원칙/원리",    example:"She lives by strong principles.",             exampleKorean:"그녀는 확고한 원칙을 가지고 살아요.",    idiom:"first principles",  idiomMeaning:"기본 원칙",       memoryTip:"프린시플~ 처음에 잡은 기준!",             difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h37", word:"conscience",     pronunciation:"/ˈkɒnʃəns/",      meaning:"양심",         example:"Let your conscience guide your actions.",     exampleKorean:"양심이 행동을 이끌도록 하세요.",          idiom:"guilty conscience", idiomMeaning:"죄책감",          memoryTip:"컨셔스~ 스스로 아는(con+scious) 양심!",  difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h38", word:"responsibility", pronunciation:"/rɪˌspɒnsɪˈbɪlɪti/", meaning:"책임",    example:"Taking responsibility shows maturity.",        exampleKorean:"책임감을 갖는 것은 성숙함을 보여줘요.",  idiom:"sense of responsibility", idiomMeaning:"책임감",      memoryTip:"리스폰서빌리티~ 결과에 응답하는 능력!",  difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h39", word:"perspective",    pronunciation:"/pərˈspɛktɪv/",   meaning:"관점/시각",    example:"Try to see things from another perspective.", exampleKorean:"다른 관점에서 사물을 보려고 해요.",       idiom:"in perspective",    idiomMeaning:"올바른 시각으로", memoryTip:"퍼스펙티브~ 무언가를 통해 보는 시각!",   difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h40", word:"judgment",       pronunciation:"/ˈdʒʌdʒmənt/",    meaning:"판단/판결",    example:"Good judgment comes from experience.",        exampleKorean:"좋은 판단력은 경험에서 나와요.",          idiom:"sound judgment",    idiomMeaning:"올바른 판단",     memoryTip:"저지먼트~ 판사(judge)처럼 결정내리기!",  difficulty:"hard",   level:"high", grade:2, unit:1, category:"윤리" },
  { id:"h41", word:"value",          pronunciation:"/ˈvæljuː/",       meaning:"가치/소중히 여기다", example:"Family and health are core values.",      exampleKorean:"가족과 건강은 핵심 가치예요.",            idiom:"value system",      idiomMeaning:"가치 체계",       memoryTip:"밸류~ 얼마나 소중한지의 척도!",           difficulty:"medium", level:"high", grade:2, unit:1, category:"윤리" },

  // Unit 2 — 심리
  { id:"h42", word:"psychology",  pronunciation:"/saɪˈkɒlədʒi/",   meaning:"심리학",         example:"Psychology helps us understand human behavior.", exampleKorean:"심리학은 인간 행동을 이해하는 데 도움이 돼요.", idiom:"social psychology", idiomMeaning:"사회 심리학",  memoryTip:"사이콜로지~ 마음(psycho)+로지(학문)!",   difficulty:"hard",     level:"high", grade:2, unit:2, category:"심리" },
  { id:"h43", word:"behavior",    pronunciation:"/bɪˈheɪvjər/",    meaning:"행동/행동 양식",  example:"Human behavior is complex and interesting.", exampleKorean:"인간의 행동은 복잡하고 흥미로워요.",        idiom:"behavior pattern",  idiomMeaning:"행동 패턴",        memoryTip:"비헤이비어~ 갖게 된(have) 행동 방식!",  difficulty:"medium",   level:"high", grade:2, unit:2, category:"심리" },
  { id:"h44", word:"motivation",  pronunciation:"/ˌmoʊtɪˈveɪʃən/", meaning:"동기/의욕",       example:"Understanding your motivation helps you succeed.", exampleKorean:"동기를 이해하면 성공하는 데 도움이 돼요.", idiom:"self-motivation", idiomMeaning:"자기 동기 부여", memoryTip:"모티베이션~ 행동의 이유(motive)!",       difficulty:"hard",     level:"high", grade:2, unit:2, category:"심리" },
  { id:"h45", word:"perception",  pronunciation:"/pərˈsɛpʃən/",    meaning:"인식/지각",       example:"Perception shapes how we see the world.",    exampleKorean:"인식은 세계를 보는 방식을 형성해요.",       idiom:"visual perception", idiomMeaning:"시각적 인식",      memoryTip:"퍼셉션~ 감각으로 잡아내는 인식!",        difficulty:"hard",     level:"high", grade:2, unit:2, category:"심리" },
  { id:"h46", word:"attitude",    pronunciation:"/ˈætɪtjuːd/",     meaning:"태도/자세",       example:"A positive attitude helps in difficult times.", exampleKorean:"긍정적인 태도는 어려운 시기에 도움이 돼요.", idiom:"attitude problem", idiomMeaning:"태도 문제",      memoryTip:"애티튜드~ 마음의 방향과 자세!",          difficulty:"medium",   level:"high", grade:2, unit:2, category:"심리" },
  { id:"h47", word:"stereotype",  pronunciation:"/ˈstɛriəˌtaɪp/",  meaning:"고정관념",        example:"We should challenge gender stereotypes.",    exampleKorean:"성별에 대한 고정관념에 도전해야 해요.",     idiom:"break stereotypes", idiomMeaning:"고정관념을 깨다",  memoryTip:"스테레오타입~ 고정된(stereo) 유형(type)!", difficulty:"hard",   level:"high", grade:2, unit:2, category:"심리" },
  { id:"h48", word:"prejudice",   pronunciation:"/ˈprɛdʒʊdɪs/",    meaning:"편견",            example:"Prejudice comes from lack of understanding.", exampleKorean:"편견은 이해 부족에서 생겨요.",              idiom:"overcome prejudice",idiomMeaning:"편견을 극복하다",  memoryTip:"프레저디스~ 미리(pre) 내리는 판단!",    difficulty:"hard",     level:"high", grade:2, unit:2, category:"심리" },
  { id:"h49", word:"cognitive",   pronunciation:"/ˈkɒɡnɪtɪv/",     meaning:"인지적인",        example:"Cognitive skills are important for learning.", exampleKorean:"인지적 능력은 학습에 중요해요.",            idiom:"cognitive development", idiomMeaning:"인지 발달",    memoryTip:"코그니티브~ 알아가는(cognize) 과정!",    difficulty:"advanced", level:"high", grade:2, unit:2, category:"심리" },

  // Unit 3 — 정치
  { id:"h50", word:"democracy",    pronunciation:"/dɪˈmɒkrəsi/",    meaning:"민주주의",     example:"Democracy gives citizens the right to vote.", exampleKorean:"민주주의는 시민에게 투표권을 줘요.",      idiom:"liberal democracy", idiomMeaning:"자유 민주주의",   memoryTip:"데모크라시~ 국민(demo)이 통치(cracy)!", difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },
  { id:"h51", word:"revolution",   pronunciation:"/ˌrɛvəˈluːʃən/", meaning:"혁명",         example:"The industrial revolution changed society.",  exampleKorean:"산업 혁명이 사회를 바꿨어요.",            idiom:"technological revolution", idiomMeaning:"기술 혁명", memoryTip:"레볼루션~ 완전히 뒤집어지는 변화!",     difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },
  { id:"h52", word:"independence", pronunciation:"/ˌɪndɪˈpɛndəns/", meaning:"독립",        example:"Korea gained independence in 1945.",          exampleKorean:"한국은 1945년에 독립을 얻었어요.",        idiom:"declaration of independence", idiomMeaning:"독립 선언", memoryTip:"인디펜던스~ 의존(depend)하지 않음!", difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },
  { id:"h53", word:"constitution", pronunciation:"/ˌkɒnstɪˈtjuːʃən/", meaning:"헌법",      example:"The constitution protects citizens' rights.", exampleKorean:"헌법은 시민의 권리를 보호해요.",          idiom:"constitutional rights", idiomMeaning:"헌법적 권리",  memoryTip:"컨스티튜션~ 법의 기틀을 세운 것!",      difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },
  { id:"h54", word:"reform",       pronunciation:"/rɪˈfɔːrm/",      meaning:"개혁/개선하다", example:"Education reform is needed in many countries.", exampleKorean:"많은 나라에서 교육 개혁이 필요해요.",  idiom:"social reform",     idiomMeaning:"사회 개혁",       memoryTip:"리폼~ 다시(re) 형태(form)를 바꾸는 개혁!", difficulty:"hard",   level:"high", grade:2, unit:3, category:"정치" },
  { id:"h55", word:"policy",       pronunciation:"/ˈpɒlɪsi/",       meaning:"정책",         example:"Environmental policy is changing globally.",  exampleKorean:"환경 정책이 전 세계적으로 변화하고 있어요.", idiom:"policy maker", idiomMeaning:"정책 입안자",   memoryTip:"폴리시~ 국가를 운영하는 방침!",          difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },
  { id:"h56", word:"sovereignty",  pronunciation:"/ˈsɒvrənti/",     meaning:"주권/자주권",  example:"National sovereignty is respected in diplomacy.", exampleKorean:"국가 주권은 외교에서 존중돼요.",     idiom:"national sovereignty", idiomMeaning:"국가 주권",     memoryTip:"소버린티~ 최고 권력(sovereign)!",        difficulty:"advanced", level:"high", grade:2, unit:3, category:"정치" },
  { id:"h57", word:"negotiate",    pronunciation:"/nɪˈɡoʊʃɪeɪt/",  meaning:"협상하다",     example:"The two leaders will negotiate a new deal.",  exampleKorean:"두 지도자가 새 협약을 협상할 거예요.",    idiom:"negotiate a deal",  idiomMeaning:"거래를 협상하다",  memoryTip:"니고시에이트~ 업무를 성사시키다!",       difficulty:"hard",     level:"high", grade:2, unit:3, category:"정치" },

  // Unit 4 — 과학혁신
  { id:"h58", word:"innovation",   pronunciation:"/ˌɪnəˈveɪʃən/",   meaning:"혁신",         example:"Technology innovation changes our daily lives.", exampleKorean:"기술 혁신은 우리 일상을 바꿔요.",      idiom:"drive innovation",  idiomMeaning:"혁신을 이끌다",    memoryTip:"이노베이션~ 새로운(inno) 것을 만드는 혁신!", difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h59", word:"artificial",   pronunciation:"/ˌɑːrtɪˈfɪʃəl/",  meaning:"인공의/인위적인", example:"Artificial intelligence is changing industries.", exampleKorean:"인공지능이 많은 산업을 바꾸고 있어요.", idiom:"artificial intelligence", idiomMeaning:"인공지능",  memoryTip:"아티피셜~ 기술(arti)로 만든 인공의 것!", difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h60", word:"intelligence", pronunciation:"/ɪnˈtɛlɪdʒəns/",  meaning:"지능/정보",     example:"Human intelligence is still superior to AI.",  exampleKorean:"인간 지능은 여전히 AI보다 우월해요.",    idiom:"artificial intelligence", idiomMeaning:"인공지능", memoryTip:"인텔리전스~ 정보 사이에서 선택하는 능력!", difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h61", word:"laboratory",   pronunciation:"/ləˈbɒrətri/",    meaning:"실험실",        example:"Scientists work in the laboratory every day.", exampleKorean:"과학자들은 매일 실험실에서 일해요.",     idiom:"laboratory test",   idiomMeaning:"실험실 테스트",    memoryTip:"래버러토리~ 일(labor)하는 장소!",         difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h62", word:"quantum",      pronunciation:"/ˈkwɒntəm/",      meaning:"양자/양자역학의",example:"Quantum computing will revolutionize technology.", exampleKorean:"양자 컴퓨팅은 기술을 혁명적으로 바꿀 거예요.", idiom:"quantum leap", idiomMeaning:"비약적 발전",   memoryTip:"퀀텀~ 물리학의 최소 단위! 퀀텀 점프!",  difficulty:"advanced", level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h63", word:"hypothesis",   pronunciation:"/haɪˈpɒθɪsɪs/",  meaning:"가설",          example:"A scientist must test every hypothesis.",      exampleKorean:"과학자는 모든 가설을 검증해야 해요.",    idiom:"test a hypothesis", idiomMeaning:"가설을 검증하다",  memoryTip:"하이파시스~ 아직 입증 안 된 이론!",      difficulty:"advanced", level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h64", word:"genome",       pronunciation:"/ˈdʒiːnoʊm/",     meaning:"유전체/게놈",   example:"Scientists have mapped the human genome.",     exampleKorean:"과학자들은 인간 유전체 지도를 완성했어요.", idiom:"genome sequencing", idiomMeaning:"유전체 시퀀싱", memoryTip:"지놈~ 유전자(gene) 전체(ome)!",          difficulty:"advanced", level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h65", word:"particle",     pronunciation:"/ˈpɑːrtɪkəl/",   meaning:"입자/분자",     example:"Atoms are made of tiny particles.",            exampleKorean:"원자는 작은 입자로 이루어져 있어요.",    idiom:"particle accelerator", idiomMeaning:"입자 가속기",  memoryTip:"파티클~ 아주 작은 부분(part+icle)!",     difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },
  { id:"h66", word:"simulation",   pronunciation:"/ˌsɪmjʊˈleɪʃən/",meaning:"시뮬레이션/모의",example:"Computer simulations model real-world events.", exampleKorean:"컴퓨터 시뮬레이션은 실제 사건을 모델링해요.", idiom:"flight simulation", idiomMeaning:"비행 시뮬레이션", memoryTip:"시뮬레이션~ 실제처럼(sim) 만들기!",  difficulty:"hard",     level:"high", grade:2, unit:4, category:"과학혁신" },

  // ══ Grade 3 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 문학
  { id:"h67", word:"metaphor",  pronunciation:"/ˈmɛtəfər/",   meaning:"은유",          example:"'Life is a journey' is a metaphor.",          exampleKorean:"'인생은 여정이다'는 은유예요.",           idiom:"mixed metaphor",  idiomMeaning:"혼합 은유",       memoryTip:"메타포~ 의미를 이어주는 표현!",         difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },
  { id:"h68", word:"symbolism", pronunciation:"/ˈsɪmbəlɪzəm/",meaning:"상징주의/상징",  example:"The dove is a symbol of peace.",              exampleKorean:"비둘기는 평화의 상징이에요.",              idiom:"use symbolism",   idiomMeaning:"상징을 사용하다", memoryTip:"심벌리즘~ 상징(symbol)으로 표현하는 것!", difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },
  { id:"h69", word:"irony",     pronunciation:"/ˈaɪrəni/",    meaning:"아이러니/반어",  example:"It is an irony that he feared success.",      exampleKorean:"그가 성공을 두려워했다는 건 아이러니해요.", idiom:"situational irony",idiomMeaning:"상황적 아이러니", memoryTip:"아이러니~ 기대와 반대되는 상황!",       difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },
  { id:"h70", word:"narrative", pronunciation:"/ˈnærətɪv/",   meaning:"서사/이야기",   example:"The narrative of the novel is gripping.",     exampleKorean:"소설의 서사가 흥미진진해요.",              idiom:"personal narrative",idiomMeaning:"개인 서사",     memoryTip:"내러티브~ 이야기를 풀어나가는 흐름!",  difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },
  { id:"h71", word:"rhetoric",  pronunciation:"/ˈrɛtərɪk/",   meaning:"수사학/수사",   example:"Good rhetoric persuades and inspires.",       exampleKorean:"좋은 수사는 설득하고 영감을 줘요.",        idiom:"political rhetoric",idiomMeaning:"정치적 수사",    memoryTip:"레토릭~ 효과적인 말의 기술!",           difficulty:"advanced", level:"high", grade:3, unit:1, category:"문학" },
  { id:"h72", word:"eloquent",  pronunciation:"/ˈɛlɪkwənt/",  meaning:"유창한/설득력 있는", example:"She gave an eloquent speech at graduation.", exampleKorean:"그녀는 졸업식에서 유창한 연설을 했어요.",  idiom:"eloquent speaker",idiomMeaning:"유창한 연사",    memoryTip:"엘로퀀트~ 잘 말하는(eloquent)!",       difficulty:"advanced", level:"high", grade:3, unit:1, category:"문학" },
  { id:"h73", word:"profound",  pronunciation:"/prəˈfaʊnd/",  meaning:"심오한/깊은",   example:"The book had a profound effect on me.",       exampleKorean:"그 책은 나에게 깊은 영향을 미쳤어요.",    idiom:"profound change", idiomMeaning:"심오한 변화",    memoryTip:"프로파운드~ 깊이 기초를 파고든!",       difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },
  { id:"h74", word:"persuade",  pronunciation:"/pərˈsweɪd/",  meaning:"설득하다",      example:"The lawyer persuaded the jury to acquit.",    exampleKorean:"변호사가 배심원단을 설득했어요.",          idiom:"be persuaded",    idiomMeaning:"설득되다",        memoryTip:"퍼스웨이드~ 완전히(per) 설득하다!",    difficulty:"hard",     level:"high", grade:3, unit:1, category:"문학" },

  // Unit 2 — 국제관계
  { id:"h75", word:"diplomacy",     pronunciation:"/dɪˈploʊməsi/",    meaning:"외교",         example:"Skillful diplomacy prevents wars.",           exampleKorean:"능숙한 외교는 전쟁을 막아요.",            idiom:"diplomatic relations", idiomMeaning:"외교 관계",   memoryTip:"디플로머시~ 공식 협의 방법!",            difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h76", word:"sanction",      pronunciation:"/ˈsæŋkʃən/",       meaning:"제재/승인",    example:"International sanctions affect the economy.", exampleKorean:"국제 제재는 경제에 영향을 미쳐요.",        idiom:"impose sanctions",  idiomMeaning:"제재를 부과하다", memoryTip:"생션~ 제재나 허가 모두 의미!",            difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h77", word:"alliance",      pronunciation:"/əˈlaɪəns/",        meaning:"동맹/연합",    example:"NATO is a military alliance.",                exampleKorean:"NATO는 군사 동맹이에요.",                 idiom:"form an alliance",  idiomMeaning:"동맹을 맺다",     memoryTip:"얼라이언스~ 함께하는(ally) 연합!",       difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h78", word:"refugee",       pronunciation:"/ˌrɛfjʊˈdʒiː/",    meaning:"난민",         example:"Many refugees fled the war-torn country.",    exampleKorean:"많은 난민이 전쟁으로 황폐해진 나라를 탈출했어요.", idiom:"refugee camp", idiomMeaning:"난민 캠프",   memoryTip:"레퓨지~ 피난처(refuge)를 찾는 사람!",   difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h79", word:"migration",     pronunciation:"/maɪˈɡreɪʃən/",   meaning:"이주/이민",    example:"Climate change is causing mass migration.",   exampleKorean:"기후 변화가 대규모 이주를 일으키고 있어요.", idiom:"climate migration", idiomMeaning:"기후 이주",    memoryTip:"마이그레이션~ 다른 곳으로 이동(migrate)!", difficulty:"hard",  level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h80", word:"humanitarian",  pronunciation:"/hjuːˌmænɪˈtɛəriən/", meaning:"인도주의적인", example:"The UN leads many humanitarian missions.", exampleKorean:"유엔은 많은 인도주의적 임무를 이끌어요.",  idiom:"humanitarian aid",  idiomMeaning:"인도주의적 지원", memoryTip:"휴머니테리안~ 인간(human)을 위한!",      difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h81", word:"multilateral",  pronunciation:"/ˌmʌltɪˈlætərəl/", meaning:"다자간의",     example:"Multilateral talks aim for a peaceful solution.", exampleKorean:"다자간 회담은 평화로운 해결을 목표로 해요.", idiom:"multilateral agreement", idiomMeaning:"다자간 협약", memoryTip:"멀티래터럴~ 여러(multi) 나라가 함께!", difficulty:"advanced", level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h82", word:"compromise",    pronunciation:"/ˈkɒmprəmaɪz/",   meaning:"타협/타협하다", example:"A compromise was reached after long talks.",  exampleKorean:"긴 협상 끝에 타협이 이루어졌어요.",       idiom:"reach a compromise",idiomMeaning:"타협에 도달하다", memoryTip:"컴프로마이즈~ 서로 양보하는 약속!",      difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },
  { id:"h83", word:"coalition",     pronunciation:"/koʊˈælɪʃən/",     meaning:"연합/연립",    example:"The coalition government ruled for five years.", exampleKorean:"연립 정부가 5년 동안 통치했어요.",       idiom:"coalition building",idiomMeaning:"연합 구축",       memoryTip:"코얼리션~ 여럿이 뭉친(coalesce) 연합!", difficulty:"hard",     level:"high", grade:3, unit:2, category:"국제관계" },

  // Unit 3 — 심화과학
  { id:"h84", word:"empirical",    pronunciation:"/ɪmˈpɪrɪkəl/",   meaning:"경험적인/실증적인", example:"Science is based on empirical evidence.", exampleKorean:"과학은 실증적 증거에 기반해요.",          idiom:"empirical study",   idiomMeaning:"실증 연구",       memoryTip:"임피리컬~ 경험(empiri)에 기반한!",       difficulty:"advanced", level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h85", word:"synthesis",    pronunciation:"/ˈsɪnθɪsɪs/",    meaning:"합성/종합",     example:"Photosynthesis is the synthesis of glucose.", exampleKorean:"광합성은 포도당의 합성이에요.",           idiom:"synthesis of ideas",idiomMeaning:"아이디어 종합",   memoryTip:"신세시스~ 여러 것을 합쳐 새것을!",       difficulty:"advanced", level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h86", word:"catalyst",     pronunciation:"/ˈkætəlɪst/",    meaning:"촉매/변화의 계기",example:"The discovery acted as a catalyst for change.", exampleKorean:"그 발견은 변화의 촉매 역할을 했어요.", idiom:"act as a catalyst",idiomMeaning:"촉매 역할을 하다", memoryTip:"캐털리스트~ 반응을 돕는 물질!",          difficulty:"hard",     level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h87", word:"molecule",     pronunciation:"/ˈmɒlɪkjuːl/",   meaning:"분자",          example:"Water is made of hydrogen molecules.",        exampleKorean:"물은 수소 분자로 이루어져 있어요.",       idiom:"molecule structure",idiomMeaning:"분자 구조",       memoryTip:"몰리큘~ 아주 작은 덩어리(mole+cule)!",  difficulty:"hard",     level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h88", word:"evolution",    pronunciation:"/ˌiːvəˈluːʃən/", meaning:"진화/발전",     example:"Darwin's theory of evolution is well known.", exampleKorean:"다윈의 진화론은 잘 알려져 있어요.",       idiom:"natural evolution", idiomMeaning:"자연 진화",       memoryTip:"이볼루션~ 시간에 따라 변화하는(evolve)!", difficulty:"hard",     level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h89", word:"genetics",     pronunciation:"/dʒɪˈnɛtɪks/",   meaning:"유전학",        example:"Genetics explains inherited diseases.",        exampleKorean:"유전학은 유전 질환을 설명해요.",          idiom:"genetic research",  idiomMeaning:"유전 연구",       memoryTip:"제네틱스~ 유전자(gene)를 연구하는 학문!", difficulty:"advanced", level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h90", word:"neuroscience", pronunciation:"/ˈnjʊəroʊˌsaɪəns/",meaning:"신경과학",    example:"Neuroscience explores how the brain works.",  exampleKorean:"신경과학은 뇌가 어떻게 작동하는지 탐구해요.", idiom:"neuroscience research", idiomMeaning:"신경과학 연구", memoryTip:"뉴로사이언스~ 신경(neuro)+과학!", difficulty:"advanced", level:"high", grade:3, unit:3, category:"심화과학" },
  { id:"h91", word:"phenomenon",   pronunciation:"/fɪˈnɒmɪnɒn/",   meaning:"현상",          example:"The northern lights are a natural phenomenon.", exampleKorean:"오로라는 자연 현상이에요.",             idiom:"unexplained phenomenon", idiomMeaning:"설명 불가한 현상", memoryTip:"피노미넌~ 눈에 나타나는(pheno) 현상!", difficulty:"hard",     level:"high", grade:3, unit:3, category:"심화과학" },

  // Unit 4 — 심화사회
  { id:"h92",  word:"propaganda",  pronunciation:"/ˌprɒpəˈɡændə/",  meaning:"선전/프로파간다",example:"Propaganda is used to influence opinions.",   exampleKorean:"선전은 여론을 영향시키는 데 사용돼요.",   idiom:"political propaganda", idiomMeaning:"정치 선전",   memoryTip:"프로파간다~ 퍼뜨리는(propagate) 생각!",  difficulty:"hard",     level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h93",  word:"ideology",    pronunciation:"/ˌaɪdiˈɒlədʒi/", meaning:"이념/이데올로기",example:"Democracy and communism are different ideologies.", exampleKorean:"민주주의와 공산주의는 다른 이념이에요.", idiom:"political ideology", idiomMeaning:"정치 이념",  memoryTip:"이데올로지~ 생각의 체계(idea+logy)!",    difficulty:"hard",     level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h94",  word:"capitalism",  pronunciation:"/ˈkæpɪtəlɪzəm/", meaning:"자본주의",       example:"Capitalism is based on private ownership.",  exampleKorean:"자본주의는 사유재산에 기반해요.",         idiom:"free market capitalism", idiomMeaning:"자유 시장 자본주의", memoryTip:"캐피털리즘~ 자본(capital)이 중심인 체제!", difficulty:"hard",   level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h95",  word:"inequality",  pronunciation:"/ˌɪnɪˈkwɒlɪti/", meaning:"불평등",         example:"Economic inequality is growing worldwide.",  exampleKorean:"경제적 불평등이 전 세계에서 커지고 있어요.", idiom:"income inequality", idiomMeaning:"소득 불평등", memoryTip:"인이퀄리티~ 평등(equality)하지 않음!",   difficulty:"hard",     level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h96",  word:"marginalized",pronunciation:"/ˈmɑːrdʒɪnəlaɪzd/",meaning:"소외된/주변화된",example:"Marginalized groups need more support.",      exampleKorean:"소외된 집단은 더 많은 지원이 필요해요.",  idiom:"marginalized community", idiomMeaning:"소외된 공동체", memoryTip:"마지날라이즈드~ 가장자리(margin)로 밀려난!", difficulty:"advanced", level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h97",  word:"systemic",    pronunciation:"/sɪˈstɛmɪk/",    meaning:"체계적인/구조적인",example:"Systemic change requires collective action.", exampleKorean:"구조적 변화는 집단적 행동이 필요해요.",   idiom:"systemic racism",   idiomMeaning:"구조적 인종주의", memoryTip:"시스테믹~ 체계(system) 전체에 걸친!",     difficulty:"hard",     level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h98",  word:"paradigm",    pronunciation:"/ˈpærədaɪm/",    meaning:"패러다임/사고 체계",example:"A new paradigm is needed to solve this.",   exampleKorean:"이를 해결하려면 새로운 패러다임이 필요해요.", idiom:"paradigm shift", idiomMeaning:"패러다임 전환", memoryTip:"패러다임~ 사고의 틀(paradigm)!",         difficulty:"advanced", level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h99",  word:"constitute",  pronunciation:"/ˈkɒnstɪtjuːt/", meaning:"구성하다/해당하다",example:"This action would constitute a crime.",       exampleKorean:"이 행동은 범죄에 해당해요.",              idiom:"constitute a threat",idiomMeaning:"위협을 구성하다", memoryTip:"컨스티튜트~ 함께 세워서(consti+tute) 이루다!", difficulty:"advanced", level:"high", grade:3, unit:4, category:"심화사회" },
  { id:"h100", word:"virtue",      pronunciation:"/ˈvɜːrtʃuː/",    meaning:"덕목/미덕",      example:"Patience is a virtue in difficult times.",   exampleKorean:"인내는 어려운 시기에 덕목이에요.",        idiom:"make a virtue of", idiomMeaning:"~을 장점으로 삼다", memoryTip:"버추~ 도덕적 장점(virtue)!",           difficulty:"hard",     level:"high", grade:3, unit:4, category:"심화사회" },

];
