import type { Word } from "../wordTypes";

// ── 중학교 어휘 (m01–m100) ────────────────────────────────────────────────────
// Grade 1: m01–m33   Grade 2: m34–m66   Grade 3: m67–m100
// 4 units per grade, 8–9 words per unit

export const MIDDLE_WORDS: Word[] = [

  // ══ Grade 1 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 성격
  { id:"m01", word:"kind",       pronunciation:"/kaɪnd/",        meaning:"친절한",       example:"She is always kind to everyone.",               exampleKorean:"그녀는 항상 모두에게 친절해요.",          idiom:"kind of",          idiomMeaning:"어느 정도",           memoryTip:"카인드~ 따뜻한 마음(kind)!",              difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m02", word:"honest",     pronunciation:"/ˈɒnɪst/",       meaning:"정직한",       example:"Always be honest with your friends.",           exampleKorean:"친구에게 항상 정직하게 대하세요.",         idiom:"honest opinion",   idiomMeaning:"솔직한 의견",         memoryTip:"어니스트~ 거짓 없이 솔직한!",             difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m03", word:"brave",      pronunciation:"/breɪv/",        meaning:"용감한",       example:"It was brave of you to speak up.",              exampleKorean:"그것을 말하는 건 용감한 거예요.",          idiom:"brave face",       idiomMeaning:"용감한 표정",         memoryTip:"브레이브~ 두려움 없이 앞으로!",           difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m04", word:"creative",   pronunciation:"/kriˈeɪtɪv/",    meaning:"창의적인",     example:"She draws very creative pictures.",             exampleKorean:"그녀는 매우 창의적인 그림을 그려요.",      idiom:"creative mind",    idiomMeaning:"창의적인 사고",       memoryTip:"크리에이티브~ 크리에이터처럼 창의적인!", difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m05", word:"confident",  pronunciation:"/ˈkɒnfɪdənt/",  meaning:"자신감 있는",  example:"Be confident when you speak in public.",        exampleKorean:"발표할 때 자신감을 가지세요.",              idiom:"confident manner", idiomMeaning:"자신있는 태도",       memoryTip:"컨피던트~ 컨피던스=자신감!",              difficulty:"medium", level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m06", word:"friendly",   pronunciation:"/ˈfrɛndli/",     meaning:"친근한/다정한",example:"He is friendly to new students.",                exampleKorean:"그는 새로운 학생들에게 친근해요.",         idiom:"friendly fire",    idiomMeaning:"아군 오사",           memoryTip:"프렌들리~ 프렌드처럼 다정한!",            difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m07", word:"shy",        pronunciation:"/ʃaɪ/",          meaning:"수줍은/내성적인",example:"She is shy around new people.",               exampleKorean:"그녀는 낯선 사람 앞에서 수줍어해요.",      idiom:"fight shy of",     idiomMeaning:"~을 피하다",          memoryTip:"샤이~ 얼굴을 가리며 수줍어하는!",        difficulty:"easy",   level:"middle", grade:1, unit:1, category:"성격" },
  { id:"m08", word:"curious",    pronunciation:"/ˈkjʊəriəs/",   meaning:"호기심 많은",  example:"Curious students ask many questions.",          exampleKorean:"호기심 많은 학생은 질문을 많이 해요.",     idiom:"curiosity killed the cat", idiomMeaning:"호기심이 화를 부른다", memoryTip:"큐리어스~ 호기심 많은 원숭이처럼!", difficulty:"medium", level:"middle", grade:1, unit:1, category:"성격" },

  // Unit 2 — 환경
  { id:"m09", word:"nature",     pronunciation:"/ˈneɪtʃər/",    meaning:"자연",         example:"We must protect nature for future generations.", exampleKorean:"미래 세대를 위해 자연을 보호해야 해요.",  idiom:"nature lover",     idiomMeaning:"자연을 사랑하는 사람", memoryTip:"네이처~ 아름다운 자연(nature)!",         difficulty:"easy",   level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m10", word:"earth",      pronunciation:"/ɜːrθ/",         meaning:"지구/땅",      example:"Earth Day is celebrated every April.",          exampleKorean:"지구의 날은 매년 4월에 기념해요.",         idiom:"down to earth",    idiomMeaning:"현실적인",            memoryTip:"어스~ 구글 어스처럼 지구 전체!",          difficulty:"easy",   level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m11", word:"pollution",  pronunciation:"/pəˈluːʃən/",   meaning:"오염",         example:"Air pollution is dangerous for health.",        exampleKorean:"대기 오염은 건강에 위험해요.",              idiom:"water pollution",  idiomMeaning:"수질 오염",           memoryTip:"폴루션~ 폴루트=오염시키다!",              difficulty:"medium", level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m12", word:"recycle",    pronunciation:"/riːˈsaɪkəl/",  meaning:"재활용하다",   example:"We recycle paper, plastic, and glass.",         exampleKorean:"종이, 플라스틱, 유리를 재활용해요.",       idiom:"recycle bin",      idiomMeaning:"재활용 통",           memoryTip:"리사이클~ 리(re)+사이클=다시 돌아오는!", difficulty:"easy",   level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m13", word:"energy",     pronunciation:"/ˈɛnərdʒi/",    meaning:"에너지",       example:"Solar energy is clean and renewable.",          exampleKorean:"태양 에너지는 깨끗하고 재생 가능해요.",    idiom:"full of energy",   idiomMeaning:"활기 넘치는",         memoryTip:"에너지~ 활동의 근원!",                    difficulty:"easy",   level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m14", word:"forest",     pronunciation:"/ˈfɒrɪst/",     meaning:"숲/산림",      example:"The Amazon forest is the largest in the world.", exampleKorean:"아마존 숲은 세계에서 가장 커요.",          idiom:"forest fire",      idiomMeaning:"산불",                memoryTip:"포레스트~ 포레스트 검프처럼 숲속을!",     difficulty:"easy",   level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m15", word:"protect",    pronunciation:"/prəˈtɛkt/",    meaning:"보호하다",     example:"We must protect endangered animals.",           exampleKorean:"멸종 위기 동물을 보호해야 해요.",          idiom:"protect and serve",idiomMeaning:"보호하고 봉사하다",   memoryTip:"프로텍트~ 프로텍션=보호!",                difficulty:"medium", level:"middle", grade:1, unit:2, category:"환경" },
  { id:"m16", word:"climate",    pronunciation:"/ˈklaɪmɪt/",    meaning:"기후",         example:"Climate change affects all living things.",     exampleKorean:"기후 변화는 모든 생물에 영향을 미쳐요.",   idiom:"climate change",   idiomMeaning:"기후 변화",           memoryTip:"클라이밋~ 지역의 날씨 패턴!",             difficulty:"medium", level:"middle", grade:1, unit:2, category:"환경" },

  // Unit 3 — 일상
  { id:"m17", word:"early",    pronunciation:"/ˈɜːrli/",      meaning:"일찍",         example:"I wake up early on school days.",         exampleKorean:"학교 있는 날은 일찍 일어나요.",    idiom:"early bird",       idiomMeaning:"일찍 일어나는 사람",  memoryTip:"얼리~ 얼리버드=일찍 일어나는 새!",  difficulty:"easy",   level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m18", word:"habit",    pronunciation:"/ˈhæbɪt/",      meaning:"습관",         example:"Reading is a good habit to develop.",    exampleKorean:"독서는 기르면 좋은 습관이에요.",   idiom:"kick the habit",   idiomMeaning:"습관을 버리다",       memoryTip:"해빗~ 자주 반복되는 행동!",         difficulty:"medium", level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m19", word:"health",   pronunciation:"/hɛlθ/",        meaning:"건강",         example:"Good health is the most important thing.", exampleKorean:"건강이 가장 중요한 거예요.",       idiom:"health conscious", idiomMeaning:"건강에 관심 많은",    memoryTip:"헬스~ 헬스장에서 건강을 지켜요!",  difficulty:"easy",   level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m20", word:"schedule", pronunciation:"/ˈʃɛdjuːl/",    meaning:"일정/시간표",  example:"I have a busy schedule this week.",      exampleKorean:"이번 주 일정이 바빠요.",           idiom:"ahead of schedule",idiomMeaning:"예정보다 일찍",       memoryTip:"스케줄~ 오늘 할 일 계획!",          difficulty:"easy",   level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m21", word:"prepare",  pronunciation:"/prɪˈpɛər/",    meaning:"준비하다",     example:"I prepare my bag the night before.",     exampleKorean:"전날 밤에 가방을 준비해요.",       idiom:"prepare for",      idiomMeaning:"~을 대비하다",        memoryTip:"프리페어~ 미리(pre) 준비!",          difficulty:"medium", level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m22", word:"routine",  pronunciation:"/ruːˈtiːn/",    meaning:"일과/루틴",    example:"My morning routine helps me start the day.", exampleKorean:"아침 루틴이 하루 시작에 도움이 돼요.", idiom:"daily routine", idiomMeaning:"일상적인 일과", memoryTip:"루틴~ 매일 반복하는 일!",           difficulty:"medium", level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m23", word:"improve",  pronunciation:"/ɪmˈpruːv/",    meaning:"향상시키다",   example:"Practice every day to improve your skills.", exampleKorean:"실력을 향상시키려면 매일 연습하세요.", idiom:"improve on",  idiomMeaning:"더 나아지다",         memoryTip:"임프루브~ 더 나아지다!",             difficulty:"medium", level:"middle", grade:1, unit:3, category:"일상" },
  { id:"m24", word:"spend",    pronunciation:"/spɛnd/",        meaning:"(시간·돈을) 쓰다", example:"I spend two hours studying after school.", exampleKorean:"방과 후 두 시간 공부하는 데 써요.", idiom:"spend time",   idiomMeaning:"시간을 보내다",       memoryTip:"스펜드~ 시간이나 돈을 사용하다!",   difficulty:"easy",   level:"middle", grade:1, unit:3, category:"일상" },

  // Unit 4 — 소통
  { id:"m25", word:"explain",  pronunciation:"/ɪkˈspleɪn/",   meaning:"설명하다",     example:"Can you explain this problem again?",         exampleKorean:"이 문제를 다시 설명해줄 수 있어요?",    idiom:"explain away",     idiomMeaning:"핑계를 대다",         memoryTip:"익스플레인~ 명확하게 밖으로(ex)!",      difficulty:"medium", level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m26", word:"discuss",  pronunciation:"/dɪˈskʌs/",     meaning:"토론하다/논의하다", example:"Let's discuss the topic together.",       exampleKorean:"주제에 대해 함께 이야기해봐요.",        idiom:"discuss in detail",idiomMeaning:"자세히 논의하다",     memoryTip:"디스커스~ 여럿이 이야기(discuss)!",     difficulty:"medium", level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m27", word:"agree",    pronunciation:"/əˈɡriː/",       meaning:"동의하다",     example:"Do you agree with my opinion?",               exampleKorean:"내 의견에 동의해요?",                   idiom:"agree to disagree",idiomMeaning:"의견 차이를 인정하다", memoryTip:"어그리~ 맞아요! 찬성!",                 difficulty:"easy",   level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m28", word:"disagree", pronunciation:"/ˌdɪsəˈɡriː/",  meaning:"반대하다",     example:"I disagree with that idea.",                  exampleKorean:"그 아이디어에 반대해요.",                idiom:"politely disagree",idiomMeaning:"정중히 반대하다",     memoryTip:"디스어그리~ 디스(dis)=반대+어그리!",   difficulty:"easy",   level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m29", word:"question", pronunciation:"/ˈkwɛstʃən/",   meaning:"질문/의문",    example:"Raise your hand if you have a question.",    exampleKorean:"질문이 있으면 손을 드세요.",             idiom:"question mark",    idiomMeaning:"물음표",              memoryTip:"퀘스천~ 물음표(?)처럼 궁금한 것!",      difficulty:"easy",   level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m30", word:"answer",   pronunciation:"/ˈɑːnsər/",      meaning:"대답/답변",    example:"Think before you give your answer.",          exampleKorean:"대답하기 전에 생각해봐요.",              idiom:"answer for",       idiomMeaning:"~에 책임지다",        memoryTip:"앤서~ 질문에 대한 해답(answer)!",       difficulty:"easy",   level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m31", word:"opinion",  pronunciation:"/əˈpɪnjən/",     meaning:"의견",         example:"Share your opinion with the class.",          exampleKorean:"반 친구들과 의견을 나눠요.",             idiom:"in my opinion",    idiomMeaning:"내 생각에는",         memoryTip:"오피니언~ 내 생각/의견(opinion)!",      difficulty:"medium", level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m32", word:"present",  pronunciation:"/ˈprɛzənt/",     meaning:"발표하다",     example:"I will present my project tomorrow.",         exampleKorean:"내일 프로젝트를 발표할 거예요.",         idiom:"present company",  idiomMeaning:"여기 있는 분들",      memoryTip:"프레젠트~ 프레젠테이션=발표!",          difficulty:"medium", level:"middle", grade:1, unit:4, category:"소통" },
  { id:"m33", word:"express",  pronunciation:"/ɪkˈsprɛs/",     meaning:"표현하다",     example:"It is important to express your feelings.",   exampleKorean:"감정을 표현하는 것이 중요해요.",         idiom:"express train",    idiomMeaning:"급행열차",            memoryTip:"익스프레스~ 빠르게 전달하다!",          difficulty:"medium", level:"middle", grade:1, unit:4, category:"소통" },

  // ══ Grade 2 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 과학
  { id:"m34", word:"experiment",pronunciation:"/ɪkˈspɛrɪmənt/",meaning:"실험",         example:"We did a science experiment today.",          exampleKorean:"오늘 과학 실험을 했어요.",               idiom:"experimental stage",idiomMeaning:"실험 단계",          memoryTip:"익스페리먼트~ 직접 해보는 실험!",       difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m35", word:"discover",  pronunciation:"/dɪˈskʌvər/",   meaning:"발견하다",     example:"Scientists discover new species every year.", exampleKorean:"과학자들은 매년 새 종을 발견해요.",       idiom:"discover a talent", idiomMeaning:"재능을 발견하다",    memoryTip:"디스커버~ 뚜껑을 열고 발견!",           difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m36", word:"research",  pronunciation:"/rɪˈsɜːrtʃ/",   meaning:"연구/조사",    example:"I will research this topic at the library.",  exampleKorean:"도서관에서 이 주제를 조사할 거예요.",    idiom:"research paper",   idiomMeaning:"연구 논문",           memoryTip:"리서치~ 거듭 찾아보는(re+search) 연구!", difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m37", word:"evidence",  pronunciation:"/ˈɛvɪdəns/",    meaning:"증거",         example:"Scientists need evidence to prove a theory.", exampleKorean:"이론을 증명하려면 증거가 필요해요.",      idiom:"lack of evidence", idiomMeaning:"증거 부족",           memoryTip:"에비던스~ 눈에 보이는 증거!",           difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m38", word:"theory",    pronunciation:"/ˈθɪəri/",       meaning:"이론",         example:"Darwin's theory changed how we see life.",    exampleKorean:"다윈의 이론은 생명관을 바꿨어요.",       idiom:"in theory",        idiomMeaning:"이론적으로",          memoryTip:"씨어리~ 체계적인 설명(theory)!",        difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m39", word:"observe",   pronunciation:"/əbˈzɜːrv/",    meaning:"관찰하다",     example:"Observe the plants growing each day.",        exampleKorean:"매일 자라는 식물을 관찰해요.",           idiom:"observation deck", idiomMeaning:"전망대",              memoryTip:"옵서브~ 꼼꼼히 살피는 관찰!",           difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m40", word:"measure",   pronunciation:"/ˈmɛʒər/",       meaning:"측정하다",     example:"Measure the length of the table.",            exampleKorean:"테이블의 길이를 측정해요.",              idiom:"measure up",       idiomMeaning:"기준에 맞다",         memoryTip:"메저~ 자로 재는 측정(measure)!",        difficulty:"medium", level:"middle", grade:2, unit:1, category:"과학" },
  { id:"m41", word:"result",    pronunciation:"/rɪˈzʌlt/",      meaning:"결과",         example:"The experiment gave surprising results.",     exampleKorean:"실험 결과가 놀라웠어요.",                idiom:"end result",       idiomMeaning:"최종 결과",           memoryTip:"리절트~ 일이 끝난 결과(result)!",       difficulty:"easy",   level:"middle", grade:2, unit:1, category:"과학" },

  // Unit 2 — 사회
  { id:"m42", word:"community",  pronunciation:"/kəˈmjuːnɪti/", meaning:"지역사회/공동체", example:"Our community helped the flood victims.",  exampleKorean:"우리 지역사회가 홍수 피해자를 도왔어요.", idiom:"community service",idiomMeaning:"봉사 활동",          memoryTip:"커뮤니티~ 함께 사는 동네!",             difficulty:"medium", level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m43", word:"culture",    pronunciation:"/ˈkʌltʃər/",    meaning:"문화",         example:"Learning a language opens a new culture.",    exampleKorean:"언어를 배우면 새 문화로 열려요.",         idiom:"culture shock",    idiomMeaning:"문화 충격",           memoryTip:"컬처~ 한 사회의 생활방식!",             difficulty:"medium", level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m44", word:"tradition",  pronunciation:"/trəˈdɪʃən/",   meaning:"전통",         example:"Chuseok is an important Korean tradition.",   exampleKorean:"추석은 중요한 한국 전통이에요.",          idiom:"family tradition", idiomMeaning:"가족 전통",           memoryTip:"트레디션~ 오랫동안 이어진 관습!",       difficulty:"medium", level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m45", word:"festival",   pronunciation:"/ˈfɛstɪvəl/",   meaning:"축제",         example:"We enjoy many festivals in autumn.",           exampleKorean:"가을에 많은 축제를 즐겨요.",              idiom:"film festival",    idiomMeaning:"영화제",              memoryTip:"페스티벌~ 즐거운 축제!",                difficulty:"easy",   level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m46", word:"language",   pronunciation:"/ˈlæŋɡwɪdʒ/",  meaning:"언어",         example:"English is a global language.",               exampleKorean:"영어는 세계 공용어예요.",                idiom:"body language",    idiomMeaning:"몸짓 언어",           memoryTip:"랭귀지~ 생각을 전달하는 도구!",         difficulty:"easy",   level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m47", word:"celebrate",  pronunciation:"/ˈsɛlɪbreɪt/",  meaning:"기념하다/축하하다", example:"We celebrate the new year with fireworks.", exampleKorean:"불꽃놀이로 새해를 기념해요.",          idiom:"celebrate success",idiomMeaning:"성공을 축하하다",     memoryTip:"셀레브레이트~ 화려하게 축하!",          difficulty:"medium", level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m48", word:"respect",    pronunciation:"/rɪˈspɛkt/",    meaning:"존중하다/존경", example:"Always respect people who are different.",    exampleKorean:"나와 다른 사람을 항상 존중하세요.",       idiom:"self-respect",     idiomMeaning:"자존감",              memoryTip:"리스펙트~ 상대를 다시(re) 살피다!",     difficulty:"medium", level:"middle", grade:2, unit:2, category:"사회" },
  { id:"m49", word:"share",      pronunciation:"/ʃɛər/",         meaning:"나누다/공유하다",example:"Share your knowledge with classmates.",      exampleKorean:"반 친구들과 지식을 나눠요.",             idiom:"share alike",      idiomMeaning:"공평하게 나누다",     memoryTip:"쉐어~ SNS 공유처럼!",                  difficulty:"easy",   level:"middle", grade:2, unit:2, category:"사회" },

  // Unit 3 — 심리
  { id:"m50", word:"emotion",    pronunciation:"/ɪˈmoʊʃən/",    meaning:"감정",         example:"It is okay to express your emotions.",       exampleKorean:"감정을 표현해도 괜찮아요.",              idiom:"emotional rollercoaster", idiomMeaning:"감정 기복",      memoryTip:"이모션~ 이모티콘=감정을 표현한 그림!", difficulty:"medium", level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m51", word:"stress",     pronunciation:"/strɛs/",        meaning:"스트레스/압박", example:"Too much homework causes stress.",           exampleKorean:"숙제가 너무 많으면 스트레스를 줘요.",    idiom:"under stress",     idiomMeaning:"스트레스를 받는",    memoryTip:"스트레스~ 줄여야 해요!",                difficulty:"easy",   level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m52", word:"worry",      pronunciation:"/ˈwʌri/",        meaning:"걱정하다",     example:"Don't worry about making small mistakes.",   exampleKorean:"작은 실수를 너무 걱정하지 마세요.",      idiom:"worry wart",       idiomMeaning:"걱정꾼",              memoryTip:"워리~ 자꾸 마음에 걸리는 것!",          difficulty:"easy",   level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m53", word:"calm",       pronunciation:"/kɑːm/",         meaning:"차분한/침착한", example:"Take a deep breath to stay calm.",           exampleKorean:"차분하게 있으려면 깊게 숨을 쉬세요.",    idiom:"calm down",        idiomMeaning:"진정하다",            memoryTip:"캄~ 고요한 호수처럼 잔잔한!",           difficulty:"easy",   level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m54", word:"courage",    pronunciation:"/ˈkʌrɪdʒ/",     meaning:"용기",         example:"It takes courage to try new things.",        exampleKorean:"새로운 것을 시도하려면 용기가 필요해요.", idiom:"pluck up courage", idiomMeaning:"용기를 내다",         memoryTip:"커리지~ 가슴(coeur=심장)에서 나오는 용기!", difficulty:"medium", level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m55", word:"overcome",   pronunciation:"/ˌoʊvərˈkʌm/",  meaning:"극복하다",     example:"She overcame her fear of public speaking.",   exampleKorean:"그녀는 발표 공포를 극복했어요.",         idiom:"overcome obstacles",idiomMeaning:"장애물을 극복하다",  memoryTip:"오버컴~ 어려움을 뛰어넘다!",            difficulty:"medium", level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m56", word:"confidence", pronunciation:"/ˈkɒnfɪdəns/",  meaning:"자신감",       example:"Practice builds confidence over time.",       exampleKorean:"연습하면 자신감이 생겨요.",              idiom:"self-confidence",  idiomMeaning:"자기 확신",           memoryTip:"컨피던스~ 나를 믿는 힘!",               difficulty:"medium", level:"middle", grade:2, unit:3, category:"심리" },
  { id:"m57", word:"goal",       pronunciation:"/ɡoʊl/",         meaning:"목표",         example:"Set a clear goal and work toward it.",        exampleKorean:"명확한 목표를 세우고 나아가세요.",       idiom:"goal-oriented",    idiomMeaning:"목표 지향적인",       memoryTip:"골~ 축구에서 넣는 골처럼 목표!",        difficulty:"easy",   level:"middle", grade:2, unit:3, category:"심리" },

  // Unit 4 — 경제
  { id:"m58", word:"price",      pronunciation:"/praɪs/",        meaning:"가격",         example:"The price of food has gone up.",              exampleKorean:"음식 가격이 올랐어요.",                  idiom:"price tag",        idiomMeaning:"가격표",              memoryTip:"프라이스~ 물건값(price)!",               difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m59", word:"cost",       pronunciation:"/kɒst/",         meaning:"비용/값",      example:"The cost of living is high in Seoul.",        exampleKorean:"서울은 생활비가 높아요.",                idiom:"at all costs",     idiomMeaning:"어떤 대가를 치르더라도", memoryTip:"코스트~ 들어가는 돈(cost)!",           difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m60", word:"buy",        pronunciation:"/baɪ/",          meaning:"구매하다",     example:"I buy groceries at the local market.",        exampleKorean:"동네 시장에서 식료품을 사요.",            idiom:"buy time",         idiomMeaning:"시간을 벌다",         memoryTip:"바이~ 쇼핑할 때 바이(buy)!",            difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m61", word:"sell",       pronunciation:"/sɛl/",          meaning:"팔다",         example:"She sells homemade cookies online.",           exampleKorean:"그녀는 수제 쿠키를 온라인으로 팔아요.",  idiom:"sell out",         idiomMeaning:"매진되다",            memoryTip:"쎌~ 팔다(sell)=셀링!",                 difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m62", word:"market",     pronunciation:"/ˈmɑːrkɪt/",    meaning:"시장",         example:"The stock market went up today.",              exampleKorean:"오늘 주식 시장이 올랐어요.",              idiom:"in the market for",idiomMeaning:"~을 원하는",          memoryTip:"마켓~ 물건 사고파는 곳!",               difficulty:"medium", level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m63", word:"business",   pronunciation:"/ˈbɪznɪs/",     meaning:"사업/비즈니스",example:"He started his own business at 25.",           exampleKorean:"그는 25살에 사업을 시작했어요.",          idiom:"business as usual",idiomMeaning:"평소처럼",            memoryTip:"비즈니스~ 일과 사업!",                  difficulty:"medium", level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m64", word:"save",       pronunciation:"/seɪv/",         meaning:"저축하다/절약하다", example:"Save money for what you really want.",   exampleKorean:"정말 원하는 것을 위해 돈을 모아요.",      idiom:"save the day",     idiomMeaning:"위기를 구하다",       memoryTip:"세이브~ 저금통에 쏙!",                  difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m65", word:"trade",      pronunciation:"/treɪd/",        meaning:"교역/무역",    example:"Korea trades with many countries.",           exampleKorean:"한국은 많은 나라와 교역을 해요.",         idiom:"trade-off",        idiomMeaning:"거래/상충",           memoryTip:"트레이드~ 물건을 서로 교환하는 것!",    difficulty:"medium", level:"middle", grade:2, unit:4, category:"경제" },
  { id:"m66", word:"popular",    pronunciation:"/ˈpɒpjʊlər/",   meaning:"인기 있는",    example:"This singer is popular among teens.",         exampleKorean:"이 가수는 10대에게 인기가 있어요.",       idiom:"popular culture",  idiomMeaning:"대중문화",            memoryTip:"파퓰러~ 많은 사람이 좋아하는!",         difficulty:"easy",   level:"middle", grade:2, unit:4, category:"경제" },

  // ══ Grade 3 ═══════════════════════════════════════════════════════════════

  // Unit 1 — 국제
  { id:"m67", word:"global",         pronunciation:"/ˈɡloʊbəl/",        meaning:"세계적인/전지구적", example:"Climate change is a global problem.",        exampleKorean:"기후 변화는 전 지구적 문제예요.",       idiom:"global village",     idiomMeaning:"지구촌",              memoryTip:"글로벌~ 지구(globe) 전체!",              difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m68", word:"international",  pronunciation:"/ˌɪntərˈnæʃənəl/", meaning:"국제적인",          example:"The UN is an international organization.",   exampleKorean:"유엔은 국제기구예요.",                  idiom:"international relations", idiomMeaning:"국제 관계",    memoryTip:"인터내셔널~ 국가들 사이(inter)!",        difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m69", word:"cooperation",    pronunciation:"/koʊˌɒpəˈreɪʃən/", meaning:"협력/협동",         example:"International cooperation solves global issues.", exampleKorean:"국제 협력은 세계 문제를 해결해요.",  idiom:"in cooperation with",idiomMeaning:"~와 협력하여",       memoryTip:"코오퍼레이션~ 함께(co) 일하기!",        difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m70", word:"peace",          pronunciation:"/piːs/",             meaning:"평화",             example:"We all hope for world peace.",               exampleKorean:"우리 모두 세계 평화를 바라요.",         idiom:"peace of mind",      idiomMeaning:"마음의 평화",         memoryTip:"피스~ 전쟁 없는 평화로운 세상!",        difficulty:"easy",   level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m71", word:"conflict",       pronunciation:"/ˈkɒnflɪkt/",       meaning:"갈등/충돌",        example:"Conflicts can be solved through dialogue.",  exampleKorean:"갈등은 대화를 통해 해결할 수 있어요.",  idiom:"conflict of interest",idiomMeaning:"이해충돌",           memoryTip:"컨플릭트~ 서로 부딪히는 갈등!",         difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m72", word:"leader",         pronunciation:"/ˈliːdər/",         meaning:"지도자/리더",      example:"A good leader listens to others.",           exampleKorean:"좋은 지도자는 남의 말을 들어요.",       idiom:"born leader",        idiomMeaning:"타고난 리더",         memoryTip:"리더~ 앞에서 이끄는 사람!",             difficulty:"easy",   level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m73", word:"nation",         pronunciation:"/ˈneɪʃən/",         meaning:"국가/나라",        example:"Korea is a nation with a rich history.",     exampleKorean:"한국은 역사가 풍부한 나라예요.",        idiom:"nation building",    idiomMeaning:"국가 건설",           memoryTip:"네이션~ 나라(nation)!",                 difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },
  { id:"m74", word:"border",         pronunciation:"/ˈbɔːrdər/",        meaning:"국경/경계",        example:"The two countries share a long border.",     exampleKorean:"두 나라는 긴 국경을 공유해요.",         idiom:"cross the border",   idiomMeaning:"국경을 넘다",         memoryTip:"보더~ 두 나라 사이의 경계선!",          difficulty:"medium", level:"middle", grade:3, unit:1, category:"국제" },

  // Unit 2 — 미디어
  { id:"m75", word:"social",    pronunciation:"/ˈsoʊʃəl/",   meaning:"사회적인/소셜",  example:"Social media connects people worldwide.",     exampleKorean:"소셜 미디어는 전 세계 사람을 연결해요.", idiom:"social butterfly",  idiomMeaning:"사교적인 사람",      memoryTip:"소셜~ 사람들과 어울리는!",              difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m76", word:"media",     pronunciation:"/ˈmiːdiə/",   meaning:"미디어/매체",    example:"The media reports news every day.",           exampleKorean:"미디어는 매일 뉴스를 보도해요.",        idiom:"mass media",        idiomMeaning:"대중 매체",           memoryTip:"미디어~ 정보를 전달하는 수단!",         difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m77", word:"digital",   pronunciation:"/ˈdɪdʒɪtəl/", meaning:"디지털",        example:"We live in a digital world.",                 exampleKorean:"우리는 디지털 세상에 살아요.",           idiom:"digital age",       idiomMeaning:"디지털 시대",         memoryTip:"디지털~ 0과 1로 이루어진 세계!",        difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m78", word:"online",    pronunciation:"/ˈɒnlaɪn/",   meaning:"온라인",        example:"Many students study online.",                 exampleKorean:"많은 학생들이 온라인으로 공부해요.",     idiom:"online shopping",   idiomMeaning:"온라인 쇼핑",         memoryTip:"온라인~ 인터넷에 연결된(on+line)!",     difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m79", word:"content",   pronunciation:"/ˈkɒntɛnt/",  meaning:"콘텐츠/내용",   example:"She creates interesting content online.",     exampleKorean:"그녀는 흥미로운 콘텐츠를 만들어요.",    idiom:"content creator",   idiomMeaning:"콘텐츠 창작자",       memoryTip:"컨텐츠~ 미디어의 내용물!",             difficulty:"medium", level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m80", word:"create",    pronunciation:"/kriˈeɪt/",   meaning:"창작하다/만들다",example:"You can create your own video online.",       exampleKorean:"온라인에서 직접 영상을 만들 수 있어요.", idiom:"create a buzz",    idiomMeaning:"화제를 만들다",       memoryTip:"크리에이트~ 새로운 것을 만들다!",       difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m81", word:"upload",    pronunciation:"/ˈʌploʊd/",   meaning:"업로드하다",    example:"I upload photos to my blog every week.",      exampleKorean:"매주 블로그에 사진을 업로드해요.",       idiom:"upload speed",      idiomMeaning:"업로드 속도",         memoryTip:"업로드~ 인터넷에 올리기(up+load)!",    difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m82", word:"influence", pronunciation:"/ˈɪnflʊəns/", meaning:"영향/영향을 미치다", example:"Social media has a big influence on teens.", exampleKorean:"소셜 미디어는 10대에게 큰 영향을 미쳐요.", idiom:"under the influence", idiomMeaning:"~의 영향 아래", memoryTip:"인플루언스~ 인플루언서처럼 영향력!",  difficulty:"medium", level:"middle", grade:3, unit:2, category:"미디어" },
  { id:"m83", word:"trend",     pronunciation:"/trɛnd/",      meaning:"트렌드/유행",   example:"Short videos are the latest trend.",          exampleKorean:"짧은 영상이 최신 유행이에요.",           idiom:"trending topic",    idiomMeaning:"화제의 주제",         memoryTip:"트렌드~ 지금 유행하는 것!",             difficulty:"easy",   level:"middle", grade:3, unit:2, category:"미디어" },

  // Unit 3 — 건강
  { id:"m84", word:"disease",   pronunciation:"/dɪˈziːz/",    meaning:"질병",         example:"Wash your hands to prevent disease.",         exampleKorean:"질병을 예방하려면 손을 씻으세요.",        idiom:"heart disease",     idiomMeaning:"심장 질환",           memoryTip:"디지즈~ 불편함(dis+ease)=질병!",        difficulty:"medium", level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m85", word:"symptom",   pronunciation:"/ˈsɪmptəm/",   meaning:"증상",         example:"Fever is a symptom of the flu.",              exampleKorean:"발열은 독감의 증상이에요.",              idiom:"symptom checker",   idiomMeaning:"증상 확인기",         memoryTip:"심프텀~ 몸이 보내는 신호!",             difficulty:"medium", level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m86", word:"treatment", pronunciation:"/ˈtriːtmənt/",  meaning:"치료",         example:"Early treatment gives better results.",       exampleKorean:"조기 치료가 더 좋은 결과를 줘요.",        idiom:"medical treatment", idiomMeaning:"의학적 치료",         memoryTip:"트리트먼트~ 치료(treat) 행위!",         difficulty:"medium", level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m87", word:"recover",   pronunciation:"/rɪˈkʌvər/",   meaning:"회복하다",     example:"It takes time to recover from illness.",      exampleKorean:"병에서 회복하는 데 시간이 걸려요.",       idiom:"recover data",      idiomMeaning:"데이터를 복구하다",   memoryTip:"리커버~ 다시(re) 덮다=회복!",           difficulty:"medium", level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m88", word:"prevent",   pronunciation:"/prɪˈvɛnt/",   meaning:"예방하다",     example:"Exercise helps prevent many diseases.",       exampleKorean:"운동은 많은 질병을 예방해요.",            idiom:"prevent from",      idiomMeaning:"~을 막다",            memoryTip:"프리벤트~ 미리(pre) 막다!",             difficulty:"medium", level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m89", word:"vitamin",   pronunciation:"/ˈvaɪtəmɪn/",  meaning:"비타민",       example:"Vitamin C helps boost your immune system.",   exampleKorean:"비타민 C는 면역력을 높여줘요.",           idiom:"vitamin supplement",idiomMeaning:"비타민 보충제",       memoryTip:"비타민~ 생명(vita)에 필요한 영양소!",   difficulty:"easy",   level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m90", word:"diet",      pronunciation:"/ˈdaɪət/",      meaning:"식단/다이어트", example:"A balanced diet keeps you healthy.",         exampleKorean:"균형 잡힌 식단이 건강을 유지시켜요.",    idiom:"diet plan",         idiomMeaning:"식단 계획",           memoryTip:"다이어트~ 건강한 식습관!",              difficulty:"easy",   level:"middle", grade:3, unit:3, category:"건강" },
  { id:"m91", word:"fitness",   pronunciation:"/ˈfɪtnɪs/",    meaning:"건강/체력",    example:"Physical fitness is important for students.", exampleKorean:"학생들에게 신체 건강이 중요해요.",        idiom:"fitness routine",   idiomMeaning:"운동 루틴",           memoryTip:"피트니스~ 몸이 딱 맞게(fit) 건강한!",  difficulty:"easy",   level:"middle", grade:3, unit:3, category:"건강" },

  // Unit 4 — 예술
  { id:"m92",  word:"author",      pronunciation:"/ˈɔːθər/",         meaning:"작가",       example:"The author of this book is famous.",          exampleKorean:"이 책의 작가는 유명해요.",              idiom:"author's note",       idiomMeaning:"작가의 말",        memoryTip:"어서~ 글을 쓰는 사람(author)!",        difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m93",  word:"novel",       pronunciation:"/ˈnɒvəl/",         meaning:"소설/새로운",example:"I read a new novel this weekend.",             exampleKorean:"이번 주말에 새 소설을 읽었어요.",        idiom:"novel approach",      idiomMeaning:"새로운 접근 방식", memoryTip:"노벨~ 새롭고(novel) 긴 이야기!",       difficulty:"easy",   level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m94",  word:"poetry",      pronunciation:"/ˈpoʊɪtri/",       meaning:"시(詩)",     example:"Poetry expresses deep feelings beautifully.", exampleKorean:"시는 깊은 감정을 아름답게 표현해요.",    idiom:"spoken poetry",       idiomMeaning:"낭독 시",          memoryTip:"포에트리~ 시인(poet)이 쓰는 것!",      difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m95",  word:"character",   pronunciation:"/ˈkærɪktər/",      meaning:"등장인물/성격", example:"The main character of the story is brave.", exampleKorean:"이야기의 주인공은 용감해요.",            idiom:"character building",  idiomMeaning:"인성 계발",        memoryTip:"캐릭터~ 만화 속 인물!",                difficulty:"easy",   level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m96",  word:"plot",        pronunciation:"/plɒt/",            meaning:"줄거리/구성",example:"The plot of the movie was surprising.",        exampleKorean:"영화 줄거리가 놀라웠어요.",              idiom:"plot twist",          idiomMeaning:"반전",             memoryTip:"플롯~ 이야기의 흐름(plot)!",            difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m97",  word:"theme",       pronunciation:"/θiːm/",            meaning:"주제",       example:"The theme of the novel is friendship.",       exampleKorean:"소설의 주제는 우정이에요.",              idiom:"theme park",          idiomMeaning:"테마파크",         memoryTip:"씸~ 이야기가 담고 있는 주제!",          difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m98",  word:"imagination", pronunciation:"/ɪˌmædʒɪˈneɪʃən/",meaning:"상상력",     example:"Great authors have strong imagination.",       exampleKorean:"훌륭한 작가들은 상상력이 풍부해요.",    idiom:"use your imagination",idiomMeaning:"상상력을 발휘하다", memoryTip:"이매지네이션~ 상상(imagine)하는 능력!", difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m99",  word:"artwork",     pronunciation:"/ˈɑːrtwɜːrk/",     meaning:"예술 작품",  example:"The museum displays famous artwork.",         exampleKorean:"박물관에 유명한 예술 작품이 전시돼요.",  idiom:"original artwork",    idiomMeaning:"원본 작품",        memoryTip:"아트워크~ 아트(art)+워크(work)!",       difficulty:"easy",   level:"middle", grade:3, unit:4, category:"예술" },
  { id:"m100", word:"inspire",     pronunciation:"/ɪnˈspaɪər/",      meaning:"영감을 주다",example:"Great music can inspire creativity.",         exampleKorean:"훌륭한 음악은 창의력에 영감을 줘요.",   idiom:"inspire others",      idiomMeaning:"다른 사람에게 영감을 주다", memoryTip:"인스파이어~ 숨을 불어넣다=영감!", difficulty:"medium", level:"middle", grade:3, unit:4, category:"예술" },

];
